ui.xrayGrey.click                = function() { if (xrayVision=="false") { xrayVision="true"; localStorage.setItem("xrayVision", "true"); } else { xrayVision="false"; localStorage.setItem("xrayVision", "false"); } };
ui.xrayMagenta.click             = function() { if (xrayVision=="false") { xrayVision="true"; localStorage.setItem("xrayVision", "true"); } else { xrayVision="false"; localStorage.setItem("xrayVision", "false"); } };
ui.xrayCyan.click                = function() { if (xrayVision=="false") { xrayVision="true"; localStorage.setItem("xrayVision", "true"); } else { xrayVision="false"; localStorage.setItem("xrayVision", "false"); } };
ui.partY.input                   = function() { if (coinFocus!=null) { coinFocus.style.top    = parseInt(ui.partY.ref.value) + "px"; coinFocus.dataset.top    = parseInt(ui.partY.ref.value) + "px"; redraw(); } };
ui.partX.input                   = function() { if (coinFocus!=null) { coinFocus.style.left   = parseInt(ui.partX.ref.value) + "px"; coinFocus.dataset.left   = parseInt(ui.partX.ref.value) + "px"; redraw(); } };
ui.partW.input                   = function() { if (coinFocus!=null) { coinFocus.style.width  = parseInt(ui.partW.ref.value) + "px"; coinFocus.dataset.width  = parseInt(ui.partW.ref.value) + "px"; redraw(); } };
ui.partH.input                   = function() { if (coinFocus!=null) { coinFocus.style.height = parseInt(ui.partH.ref.value) + "px"; coinFocus.dataset.height = parseInt(ui.partH.ref.value) + "px"; redraw(); } };
ui.cursorAuto.click              = function() { useCustomCursors = false;                               cursorSetup(); };
ui.cursorXS.click                = function() { useCustomCursors = true ; cursorSet = cursorSize[0][0]; cursorSetup(); };
ui.cursorS.click                 = function() { useCustomCursors = true ; cursorSet = cursorSize[1][0]; cursorSetup(); };
ui.cursorM.click                 = function() { useCustomCursors = true ; cursorSet = cursorSize[2][0]; cursorSetup(); };
ui.cursorL.click                 = function() { useCustomCursors = true ; cursorSet = cursorSize[3][0]; cursorSetup(); };
ui.cursorXL.click                = function() { useCustomCursors = true ; cursorSet = cursorSize[4][0]; cursorSetup(); };
ui.cursorNum.click               = function() {  };
ui.partNom.input                 = function() { if (coinFocus != null && curFocus ==0) { coinFocus.id = ui.partNom.ref.value; } };
ui.partPrev.click                = function() { focusPrevious(); updateInfoShelf(); redraw(); };
ui.partNext.click                = function() { focusNext();     updateInfoShelf(); redraw(); };
ui.partText.input                = function() { if (coinFocus!=null) { if (curFocus==0) { coinFocus.dataset.notes = ui.partText.ref.value; } } };