z_wizardCode.g_wizard = {};
z_wizardCode.g_wizard.a_documentation = `
This is filled with some pretty important stuff that essentially matches W E Z M in style mode.
`;
z_wizardCode.g_wizard.b_code = `
<div id="coin82516" data-js-name="coin82516" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="0px" data-width="384px" data-height="48px" style="position: absolute; z-index: 100250900; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 0px; width: 384px; height: 48px; outline: none;" data-coin-trip="?" data-flow="0"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: inherit; outline: grey solid 4px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: white; color: rgb(0, 0, 0); font-size: 32px; text-shadow: rgba(127, 127, 127, 0.75) 1px 1px 1px;" contenteditable="false">Important Options:</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin09310" data-js-name="coin09310" data-parent="coin36032" data-children="coin71228" data-finished-outline="none" data-drag-pull="div.contentEditable" data-wrapper="undefined" data-outline-colour="grey" data-file-include="a_setEditableTrue.html" data-width="240px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251000; user-select: none; left: 0px; top: 48px; width: 240px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="48px" data-coin-trip="1" data-flow="1"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey solid 2px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);" contenteditable="false"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: green;" onclick="
try { 
window.opener.coinFocus.div.contentEditable='true';
} catch {};
">editable true</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin32924" data-js-name="coin32924" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="240px" data-top="48px" data-width="144px" data-height="336px" style="position: absolute; z-index: 100251100; user-select: none; transform-origin: left top; transform: scale(1); left: 240px; top: 48px; width: 144px; height: 336px; outline: none;" data-coin-trip="?" data-flow="2"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: auto; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: inherit; outline: grey dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0); font-size: 24px; text-shadow: rgba(127, 127, 127, 0.75) 0.75px 0.75px 0.75px; padding: 12px;" contenteditable="false">These buttons may be convenient sometimes but, I will also point out the corresponding keyboard keys are: "E for editable, W for user-select, M for overflow, and Z for anchor". (use style-mode, caps lock off) Further: If you hold the 'shift' key also, the action will go to the entire group. This is faster.</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin71228" data-js-name="coin71228" data-parent="coin09310" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="b_setEditableFalse.html" data-width="240px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251200; user-select: none; left: 0px; top: 80px; width: 240px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="80px" data-coin-trip="1" data-flow="3"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey solid 2px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);" contenteditable="false"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: red;" onclick="
try { 
window.opener.coinFocus.div.contentEditable='false';
} catch {};
">editable false</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin15621" data-js-name="coin15621" data-parent="coin36032" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="d_overflowAuto.html" data-width="240px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251300; user-select: none; left: 0px; top: 128px; width: 240px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="128px" data-coin-trip="1" data-flow="4"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey solid 2px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);" contenteditable="false"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: green;" onclick="
try { 
window.opener.coinFocus.main.style.overflow='auto';
} catch {};
">overflow auto</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin13143" data-js-name="coin13143" data-parent="coin36032" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="c_overflowHidden.html" data-width="240px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251400; user-select: none; left: 0px; top: 160px; width: 240px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="160px" data-coin-trip="1" data-flow="5"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey solid 2px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);" contenteditable="false"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: red;" onclick="
try { 
window.opener.coinFocus.main.style.overflow='hidden';
} catch {};
">overflow hidden</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin16922" data-js-name="coin16922" data-parent="coin36032" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="e_overflowVisible.html" data-width="240px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251500; user-select: none; left: 0px; top: 192px; width: 240px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="192px" data-coin-trip="1" data-flow="6"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey solid 2px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: black;" contenteditable="false"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: black;" onclick="
try { 
window.opener.coinFocus.main.style.overflow='visible';
} catch {};
">overflow visible</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin22473" data-js-name="coin22473" data-parent="coin36032" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="g_userSelectAuto.html" data-width="240px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251600; user-select: none; left: 0px; top: 240px; width: 240px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="240px" data-coin-trip="1" data-flow="7"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey solid 2px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);" contenteditable="false"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: green;" onclick="
try { 
window.opener.coinFocus.style.userSelect='auto';
} catch {};
">user-select auto</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin18178" data-js-name="coin18178" data-parent="coin36032" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="f_userSelectNone.html" data-width="240px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251700; user-select: none; left: 0px; top: 272px; width: 240px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="272px" data-coin-trip="1" data-flow="8"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey solid 2px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);" contenteditable="false"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: red;" onclick="
try { 
window.opener.coinFocus.style.userSelect='none';
} catch {};
">user-select none</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin90155" data-js-name="coin90155" data-parent="coin36032" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="i_anchorHigh.html" data-width="240px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251800; user-select: none; left: 0px; top: 320px; width: 240px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="320px" data-coin-trip="1" data-flow="9"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey solid 2px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);" contenteditable="false"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: green;" onclick="
try { 
window.opener.coinFocus.anchor.style.zIndex='300';
} catch {};
">anchor high</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin36032" data-js-name="coin36032" data-drag-pull="backgroundColor" data-parent="" data-children="coin08059,coin09310,coin13143,coin15621,coin16922,coin18178,coin22473,coin90155" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="352px" data-width="240px" data-height="32px" style="position: absolute; z-index: 100251900; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 352px; width: 240px; height: 32px; outline: none;" data-coin-trip="1" data-file-include="h_anchorLow.html" data-flow="10"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey solid 2px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);" contenteditable="false"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: red;" onclick="
try { 
window.opener.coinFocus.anchor.style.zIndex='0';
} catch {};
">anchor low</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>
`;
