                                                                          shelfMenuHTML.tab4.folderSelectors.style = "\n" + `<style>
.button_folder41button           { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII="); position: absolute; border: none; margin: none; padding: none; left:      5px; top:     37px; width:     94px; height:     28px; }
.button_folder41button:focus     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII=");  }
.button_folder41button:hover     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAALhJREFUSIntlMsWgCAIRGXVYv7/fyulhygqprVpFh4iuOLU0blfDaKgKKSbtLJslcYXIaWtIlSqDHgt5QopK77EEuZ14Q/YTDx9jK94L34BAz7qm4dX6K+Y8xSv81vw+VEzQ5jxNBUfp0ip6vSe5MtTacaKF319+LRcv8mPVFpVuPCbhIf9b+MB7FC/7A9bAN5nwF7gBX4fJgb2kJOApxZHGOcTH+DCLwtGTR8sYV98yB/ATf+NqloB2B0Fo0fFXXoAAAAASUVORK5CYII=");  }
.button_folder41button:active    { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAALhJREFUSIntlMsWgCAIRN21GP7/eyulhygqprVpFh4iuOLU0blfDaKgKKSbtLJslcYXIaWtIlSqDHgt5QopK77EEuZ14Q/YTDx9jK94L34BAz7qm4dX6K+Y8xSv81vw+VEzQ5jxNBUfp0ip6vSe5MtTacaKF319+LRcv8mPVFpVuPCbhIf9b+MB7FC/7A9bAN5nwF7gBX4fJgb2kJOApxZHGOcTH+DCLwtGTR8sYV98yB/ATf+NqloBJzckv0sD3/gAAAAASUVORK5CYII="); }




.button_folder42button           { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII="); position: absolute; border: none; margin: none; padding: none; left:    101px; top:     37px; width:     94px; height:     28px; }
.button_folder42button:focus     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII=");  }
.button_folder42button:hover     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAANdJREFUSIntlDEShUAIQ5di739lC0eXhAS1sXDExr+Q8JbBP8YfH4iYx6OyZzJaTfoNuSWXHTAtDyf0I6Bo/XWSNA09uwfakxybHurcE99WJdYCfQIGeuVEKKW/oOfDMjyJwlfON2F/10NNx81D2TRLJenDTMnQ6w5yoRx9uztYxgMDRTlR7rO44uByHSrsfXRklPUODnfonb2gn9gU+R7S7wK+iacf5N6QUPtU6Gef/9fY4Grrb2xOoXcGBQeMrMbRCxKZdkzlK7owUPMpKU7qGbQGf7weGzeAC6/JhAviAAAAAElFTkSuQmCC");  }
.button_folder42button:active    { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAANlJREFUSIntlEsOxDAIQ5Gy5f7nncWoCTY2alcjjUo3LZ+HQ1AjXvsDy3U996PbmeygipMoO8goOhNc1DpHvgBpSUY90xPxu1ypv6DVSblLelE95dWPwl+UG8x06vWdt/KuE+ehWMOtk9BNdfNQ07e3YtSnmZKfhOgg18GpH3cHJ8QDUwt1GIq+GhVPVhEoqDHmvai55x0E3lHv8EJ9YlMEPFT/jfNJvPog+pSK4kqdnz2EWL/aG71Vdhn8dvSIj+qmg3qRKvmuiP75nh9s5lwqqGcwsF/7gX0AXFEdKUaRPTIAAAAASUVORK5CYII="); }
</style>
`;
