z_wizardCode.f_wizard = {};
z_wizardCode.f_wizard.a_documentation = `
This one gets some of the tripartite setting buttons and then some different colour setting buttons.

... this eventually became all about colours and gradients ...

the other setting buttons are probably just confusing now
`;
z_wizardCode.f_wizard.b_code = `
<div id="coin99084" data-js-name="coin99084" data-parent="coin80750" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="orchid" data-file-include="b_setPink.html" data-width="192px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100250000; user-select: none; left: 0px; top: 4px; width: 192px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="4px" data-coin-trip="?" data-flow="0"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: orchid dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: orchid; font-weight: bold;" onclick="
try { 
window.opener.coinFocus.dataset.coinTrip=Ts1;
window.opener.readCoins();
window.opener.recoverColouration();
} catch {};
">set PINK</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin88131" data-js-name="coin88131" data-drag-pull="backgroundColor" data-parent="" data-children="coin00821" data-scale="1" data-finished-outline="none" data-outline-colour="seagreen" data-left="192px" data-top="4px" data-width="192px" data-height="32px" style="position: absolute; z-index: 100250400; user-select: none; transform-origin: left top; transform: scale(1); left: 192px; top: 4px; width: 192px; height: 32px; outline: none;" data-coin-trip="?" data-file-include="e_cycleColours.html" data-flow="1"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: seagreen dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: green; font-weight: bold;" onclick="
try { 
window.opener.swapColours();
} catch {};
">cycle COLOURS</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin00821" data-js-name="coin00821" data-parent="coin88131" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="a_setGrey.html" data-width="192px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100250200; user-select: none; left: 0px; top: 36px; width: 192px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="36px" data-coin-trip="?" data-flow="2"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: grey; font-weight: bold;" onclick="
try { 
window.opener.coinFocus.dataset.coinTrip=Ts0;
window.opener.readCoins();
window.opener.recoverColouration();
} catch {};
">set GREY</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin80750" data-js-name="coin80750" data-drag-pull="backgroundColor" data-parent="" data-children="coin99084" data-scale="1" data-finished-outline="none" data-outline-colour="navy" data-left="192px" data-top="36px" data-width="192px" data-height="32px" style="position: absolute; z-index: 100250500; user-select: none; transform-origin: left top; transform: scale(1); left: 192px; top: 36px; width: 192px; height: 32px; outline: none;" data-coin-trip="?" data-file-include="d_setAllColours.html" data-flow="3"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: navy dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: black; font-weight: bold;" onclick="
try { 
window.opener.assignAllColours();
} catch {};
">set all COLOURS</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin02159" data-js-name="coin02159" data-parent="coin29760" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="royalblue" data-file-include="c_setBlue.html" data-width="192px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100250300; user-select: none; left: 0px; top: 68px; width: 192px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="68px" data-coin-trip="?" data-flow="4"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: royalblue dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: blue; font-weight: bold;" onclick="
try { 
window.opener.coinFocus.dataset.coinTrip=Ts2;
window.opener.readCoins();
window.opener.recoverColouration();
} catch {};
">set BLUE</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin38846" data-js-name="coin38846" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="256px" data-top="68px" data-width="128px" data-height="192px" style="position: absolute; z-index: 100250100; user-select: none; transform-origin: left top; transform: scale(1); left: 256px; top: 68px; width: 128px; height: 192px; outline: none;" data-coin-trip="?" data-flow="5"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: auto; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: left; background-color: transparent; color: rgb(0, 0, 0); padding: 8px; font-size: 16px; text-shadow: rgba(127, 127, 127, 0.75) 0.5px 0.5px 0.5px;" contenteditable="false"><u>Notes for this Wizard:</u><h2>Use 'u' to unwrap this part.</h2>The colours are for specific destinations on the target part. The transfer happens immediately but, the one that is the most useful is the one marked 'general colour'. That one can be used with the 'TAB' key to drag the colour onto another part by using 'ctrl' or 'alt' to put it to either the 'text colour' or 'outline colour'. If you also use the 'shift' key, then it goes to the whole group. To apply it to the background colour, do not hold down any modifier keys, and just drag onto the desired part. Of course, set the colour in the box first.</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin40009" data-js-name="coin40009" data-drag-pull="div.style.background" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="108px" data-width="120px" data-height="96px" style="position: absolute; z-index: 100251300; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 108px; width: 120px; height: 96px; outline: none;" data-coin-trip="?" data-file-include="j_linearFade.html" data-flow="6"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background: linear-gradient(90deg, rgba(0, 0, 0, 0) 10%, rgb(0, 255, 0)); color: rgb(0, 0, 0);"><div style="line-height:0;">
<button class="xqnBTN" style="font: inherit; width: 100%; height: 32px; margin: 0px; padding: 0px; border: 0px; background: linear-gradient(90deg, rgba(0, 0, 0, 0) 10%, rgb(0, 255, 0));" onclick="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(' + this.nextElementSibling.nextElementSibling.value + 'deg,rgba(0,0,0,0),' + this.nextElementSibling.value + ' 90%)';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0) 10%,' + this.nextElementSibling.nextElementSibling.value + ' 90%)';
this.parentNode.firstElementChild.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0) 10%,' + this.nextElementSibling.nextElementSibling.value + ' 90%)';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
">set fade</button>

<input name="colour" type="color" style="width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="#00ff00" oninput="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0) 10%,' + this.value + ' 90%)';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0) 10%,' + this.value + ')';
this.parentNode.firstElementChild.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0) 10%,' + this.value + ')';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="range" style="width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" min="0" max="360" step="15" value="90" oninput="   
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(' + this.value + 'deg,rgba(0,0,0,0) 10%,' + this.previousElementSibling.value + ' 90%)';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(' + this.value + 'deg,rgba(0,0,0,0) 10%,' + this.previousElementSibling.value + ')';
this.parentNode.firstElementChild.style.background= 'linear-gradient(' + this.value + 'deg,rgba(0,0,0,0) 10%,' + this.previousElementSibling.value + ')';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="value" style="font: inherit; text-align: center; width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="set fade" oninput="this.setAttribute('value',this.value);this.parentNode.firstElementChild.innerHTML=this.value;">
</div></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin68709" data-js-name="coin68709" data-parent="coin48729" data-children="coin56738" data-finished-outline="none" data-drag-pull="div.style.background" data-wrapper="undefined" data-outline-colour="grey" data-file-include="k_fade2fade.html" data-width="120px" data-height="96px" data-scale="1" style="position: absolute; z-index: 100251200; user-select: none; left: 128px; top: 108px; width: 120px; height: 96px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="128px" data-top="108px" data-coin-trip="?" data-flow="7"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background: linear-gradient(0deg, rgba(0, 0, 0, 0), rgb(0, 255, 255), rgba(0, 0, 0, 0)); color: rgb(0, 0, 0);"><div style="line-height:0;">
<button class="xqnBTN" style="font: inherit; width: 100%; height: 32px; margin: 0px; padding: 0px; border: 0px; background: linear-gradient(0deg, rgba(0, 0, 0, 0), rgb(0, 255, 255), rgba(0, 0, 0, 0));" onclick="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(' + this.nextElementSibling.nextElementSibling.value + 'deg,rgba(0,0,0,0),' + this.nextElementSibling.value + ',rgba(0,0,0,0))';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0),' + this.nextElementSibling.nextElementSibling.value + ',rgba(0,0,0,0))';
this.parentNode.firstElementChild.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0),' + this.nextElementSibling.nextElementSibling.value + ',rgba(0,0,0,0))';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
">double fade</button>

<input name="colour" type="color" style="width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="#00ffff" oninput="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0),' + this.value + ',rgba(0,0,0,0))';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0),' + this.value + ',rgba(0,0,0,0))';
this.parentNode.firstElementChild.style.background= 'linear-gradient(' + this.nextElementSibling.value + 'deg,rgba(0,0,0,0),' + this.value + ',rgba(0,0,0,0))';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="range" style="width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" min="0" max="540" step="5" value="0" oninput="   
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(' + this.value + 'deg,rgba(0,0,0,0),' + this.previousElementSibling.value + ',rgba(0,0,0,0))';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(' + this.value + 'deg,rgba(0,0,0,0),' + this.previousElementSibling.value + ',rgba(0,0,0,0))';
this.parentNode.firstElementChild.style.background= 'linear-gradient(' + this.value + 'deg,rgba(0,0,0,0),' + this.previousElementSibling.value + ',rgba(0,0,0,0))';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="value" style="font: inherit; text-align: center; width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="double fade" oninput="this.setAttribute('value',this.value);this.parentNode.firstElementChild.innerHTML=this.value;">
</div></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin26331" data-js-name="coin26331" data-drag-pull="div.style.background" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="212px" data-width="120px" data-height="64px" style="position: absolute; z-index: 100251400; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 212px; width: 120px; height: 64px; outline: none;" data-coin-trip="?" data-file-include="l_linearGradient-0.html" data-flow="8"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background: linear-gradient(rgb(255, 0, 0), rgb(0, 0, 0)); color: rgb(0, 0, 0);"><div style="line-height:0;">
<button class="xqnBTN" style="font: inherit; width: 100%; height: 32px; margin: 0px; padding: 0px; border: 0px; background: linear-gradient(rgb(255, 0, 0), rgb(0, 0, 0));" onclick="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(' + this.nextElementSibling.value + ',' + this.nextElementSibling.nextElementSibling.value + ')';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(' + this.nextElementSibling.value + ',' + this.nextElementSibling.nextElementSibling.value + ')';
this.parentNode.firstElementChild.style.background= 'linear-gradient(' + this.nextElementSibling.value + ',' + this.nextElementSibling.nextElementSibling.value + ')';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
">V grad.</button>

<input name="colour" type="color" style="width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="#ff0000" oninput="   
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(' + this.value + ',' + this.nextElementSibling.value + ')';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(' + this.value + ',' + this.nextElementSibling.value + ')';
this.parentNode.firstElementChild.style.background= 'linear-gradient(' + this.value + ',' + this.nextElementSibling.value + ')';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="color" style="width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="#000000" oninput="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(' + this.previousElementSibling.value + ',' + this.value + ')';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(' + this.previousElementSibling.value + ',' + this.value + ')';
this.parentNode.firstElementChild.style.background= 'linear-gradient(' + this.previousElementSibling.value + ',' + this.value + ')';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="value" style="font: inherit; text-align: center; width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="V grad." oninput="this.setAttribute('value',this.value);this.parentNode.firstElementChild.innerHTML=this.value;">
</div></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin78895" data-js-name="coin78895" data-parent="coin87463" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="undefined" data-width="128px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251000; user-select: none; left: 256px; top: 260px; width: 128px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="256px" data-top="260px" data-coin-trip="?" data-flow="9"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; border-radius: inherit; outline: grey dashed 3px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: white; color: rgb(0, 0, 0); font-size: 24px; text-shadow: rgba(127, 127, 127, 0.75) 0.75px 0.75px 0.75px;">general colour</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin29006" data-js-name="coin29006" data-drag-pull="div.style.background" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="272px" data-width="120px" data-height="64px" style="position: absolute; z-index: 100251500; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 272px; width: 120px; height: 64px; outline: none;" data-coin-trip="?" data-file-include="m_linearGradient-1.html" data-flow="10"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background: linear-gradient(90deg, rgb(255, 255, 255), rgb(0, 0, 0)); color: rgb(0, 0, 0);"><div style="line-height:0;">
<button class="xqnBTN" style="font: inherit; width: 100%; height: 32px; margin: 0px; padding: 0px; border: 0px; background: linear-gradient(90deg, rgb(255, 255, 255), rgb(0, 0, 0));" onclick="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(90deg,' + this.nextElementSibling.value + ',' + this.nextElementSibling.nextElementSibling.value + ')';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(90deg,' + this.nextElementSibling.value + ',' + this.nextElementSibling.nextElementSibling.value + ')';
this.parentNode.firstElementChild.style.background= 'linear-gradient(90deg,' + this.nextElementSibling.value + ',' + this.nextElementSibling.nextElementSibling.value + ')';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
">H grad.</button>

<input name="colour" type="color" style="width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="#ffffff" oninput="   
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(90deg,' + this.value + ',' + this.nextElementSibling.value + ')';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(90deg,' + this.value + ',' + this.nextElementSibling.value + ')';
this.parentNode.firstElementChild.style.background= 'linear-gradient(90deg,' + this.value + ',' + this.nextElementSibling.value + ')';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="color" style="width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="#000000" oninput="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'linear-gradient(90deg,' + this.previousElementSibling.value + ',' + this.value + ')';
} catch {}
this.parentNode.parentNode.style.background= 'linear-gradient(90deg,' + this.previousElementSibling.value + ',' + this.value + ')';
this.parentNode.firstElementChild.style.background= 'linear-gradient(90deg,' + this.previousElementSibling.value + ',' + this.value + ')';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="value" style="font: inherit; text-align: center; width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="H grad." oninput="this.setAttribute('value',this.value);this.parentNode.firstElementChild.innerHTML=this.value;">
</div></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin32995" data-js-name="coin32995" data-parent="coin96199" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="I_input_color_general.html" data-width="128px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100250900; user-select: none; left: 256px; top: 292px; width: 128px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="256px" data-top="292px" data-coin-trip="?" data-flow="11"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: rgb(255, 0, 0); color: rgb(0, 0, 0);"><input type="color" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" oninput="this.setAttribute('value',this.value);this.parentNode.style.backgroundColor = this.value;" value="#ff0000">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin13449" data-js-name="coin13449" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="324px" data-width="128px" data-height="32px" style="position: absolute; z-index: 100251600; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 324px; width: 128px; height: 32px; outline: none;" data-coin-trip="?" data-flow="12"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; border-radius: inherit; outline: grey dashed 3px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: white; color: rgb(0, 0, 0); font-size: 24px; text-shadow: rgba(127, 127, 127, 0.75) 0.75px 0.75px 0.75px;">Text Colour</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin15419" data-js-name="coin15419" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="128px" data-top="324px" data-width="128px" data-height="32px" style="position: absolute; z-index: 100251900; user-select: none; transform-origin: left top; transform: scale(1); left: 128px; top: 324px; width: 128px; height: 32px; outline: none;" data-coin-trip="?" data-flow="13"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey dashed 3px; border-radius: inherit; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: white; color: rgb(0, 0, 0); font-size: 24px; text-shadow: rgba(127, 127, 127, 0.75) 0.75px 0.75px 0.75px;">BG Colour</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin17014" data-js-name="coin17014" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="256px" data-top="324px" data-width="128px" data-height="32px" style="position: absolute; z-index: 100251100; user-select: none; transform-origin: left top; transform: scale(1); left: 256px; top: 324px; width: 128px; height: 32px; outline: none;" data-coin-trip="?" data-flow="14"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; border-radius: inherit; outline: grey dashed 3px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: white; color: rgb(0, 0, 0); font-size: 24px; text-shadow: rgba(127, 127, 127, 0.75) 0.75px 0.75px 0.75px;">Outline Colour</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin23401" data-js-name="coin23401" data-parent="coin40296" data-children="" data-finished-outline="none" data-drag-pull="div.style.color" data-wrapper="undefined" data-outline-colour="grey" data-file-include="g_FGcolour.html" data-width="128px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100250600; user-select: none; left: 0px; top: 356px; width: 128px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="356px" data-coin-trip="?" data-flow="15"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(62, 33, 176);"><input type="color" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" oninput="
this.setAttribute('value',this.value);
this.parentNode.parentNode.parentNode.dataset.dragPull='div.style.color';
this.parentNode.style.color=this.value;
try {
window.opener.coinFocus.div.style.color=this.value;
} catch {};
" value="#3e21b0">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin42168" data-js-name="coin42168" data-parent="coin77969" data-children="" data-finished-outline="none" data-drag-pull="div.style.backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="f_BGcolour.html" data-width="128px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100250700; user-select: none; left: 128px; top: 356px; width: 128px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="128px" data-top="356px" data-coin-trip="?" data-flow="16"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: rgb(74, 176, 86); color: rgb(0, 0, 0);"><input type="color" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" oninput="
this.setAttribute('value',this.value);
this.parentNode.parentNode.parentNode.dataset.dragPull='div.style.backgroundColor';
this.parentNode.style.backgroundColor=this.value;
try {
window.opener.coinFocus.div.style.backgroundColor=this.value;
} catch {};
" value="#4ab056">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin77969" data-js-name="coin77969" data-drag-pull="main.style.outlineColor,dataset.outlineColour" data-parent="" data-children="coin40296,coin42168" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="256px" data-top="356px" data-width="128px" data-height="32px" style="position: absolute; z-index: 100250800; user-select: none; transform-origin: left top; transform: scale(1); left: 256px; top: 356px; width: 128px; height: 32px; outline: none;" data-coin-trip="?" data-flow="17" data-file-include="h_outlineColour.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline-color: rgb(0, 0, 0);"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><input type="color" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" oninput="
this.setAttribute('value',this.value);
try {
window.opener.coinFocus.lastElementChild.style.outlineColor=this.value;
window.opener.coinFocus.dataset.outlineColour=this.value;
} catch {};
this.parentNode.parentNode.parentNode.dataset.dragPull='main.style.outlineColor,dataset.outlineColour';
this.parentNode.parentNode.style.outlineColor=this.value;
" value="#000000">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin72157" data-js-name="coin72157" data-parent="coin40422" data-children="" data-finished-outline="none" data-drag-pull="div.style.background" data-wrapper="undefined" data-outline-colour="grey" data-file-include="n_radialFade-0.html" data-width="120px" data-height="56px" data-scale="1" style="position: absolute; z-index: 100252000; user-select: none; left: 128px; top: 212px; width: 120px; height: 56px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="128px" data-top="212px" data-coin-trip="?" data-flow="19"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background: radial-gradient(rgb(255, 0, 255), rgba(0, 0, 0, 0) 66%); color: rgb(0, 0, 0);"><div style="line-height:0;">
<button class="xqnBTN" style="font: inherit; width: 100%; height: 32px; margin: 0px; padding: 0px; border: 0px; background: radial-gradient(rgb(255, 0, 255), rgba(0, 0, 0, 0) 66%);" onclick="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'radial-gradient(' + this.nextElementSibling.value + ',rgba(0,0,0,0) 66%)';
} catch {}
this.parentNode.parentNode.style.background= 'radial-gradient(' + this.nextElementSibling.value + ',rgba(0,0,0,0) 66%)';
this.parentNode.firstElementChild.style.background= 'radial-gradient(' + this.nextElementSibling.value + ',rgba(0,0,0,0) 66%)';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
">RAD.0</button>

<input name="colour" type="color" style="width: 100%; height: 64px; margin: 0; padding: 0; border: 0;" value="#ff00ff" oninput="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'radial-gradient(' + this.value + ',rgba(0,0,0,0) 66%)';
} catch {}
this.parentNode.parentNode.style.background= 'radial-gradient(' + this.value + ',rgba(0,0,0,0) 66%)';
this.parentNode.firstElementChild.style.background=  'radial-gradient(' + this.value + ',rgba(0,0,0,0) 66%)';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="value" style="font: inherit; text-align: center; width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="RAD.0" oninput="this.setAttribute('value',this.value);this.parentNode.firstElementChild.innerHTML=this.value;">
</div></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin40422" data-js-name="coin40422" data-drag-pull="div.style.background" data-parent="" data-children="coin72157" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="128px" data-top="272px" data-width="120px" data-height="56px" style="position: absolute; z-index: 100251700; user-select: none; transform-origin: left top; transform: scale(1); left: 128px; top: 272px; width: 120px; height: 56px; outline: none;" data-coin-trip="?" data-file-include="o_radialFade-1.html" data-flow="20"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background: radial-gradient(rgba(0, 0, 0, 0), rgb(255, 0, 255) 66%); color: rgb(0, 0, 0);"><div style="line-height:0;">
<button class="xqnBTN" style="font: inherit; width: 100%; height: 32px; margin: 0px; padding: 0px; border: 0px; background: radial-gradient(rgba(0, 0, 0, 0), rgb(255, 0, 255) 66%);" onclick="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'radial-gradient(rgba(0,0,0,0),' + this.nextElementSibling.value + ' 66%)';
} catch {}
this.parentNode.parentNode.style.background= 'radial-gradient(rgba(0,0,0,0),' + this.nextElementSibling.value + ' 66%)';
this.parentNode.firstElementChild.style.background= 'radial-gradient(rgba(0,0,0,0),' + this.nextElementSibling.value + ' 66%)';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
">RAD.0</button>

<input name="colour" type="color" style="width: 100%; height: 64px; margin: 0; padding: 0; border: 0;" value="#ff00ff" oninput="
try {
window.opener.coinFocus.lastElementChild.firstElementChild.nextElementSibling.style.background= 'radial-gradient(rgba(0,0,0,0),' + this.value + ' 66%)';
} catch {}
this.parentNode.parentNode.style.background= 'radial-gradient(rgba(0,0,0,0),' + this.value + ' 66%)';
this.parentNode.firstElementChild.style.background= 'radial-gradient(rgba(0,0,0,0),' + this.value + ' 66%)';
this.parentNode.parentNode.parentNode.parentNode.dataset.dragPull='div.style.background';
this.setAttribute('value',this.value);
">

<input name="colour" type="value" style="font: inherit; text-align: center; width: 100%; height: 32px; margin: 0; padding: 0; border: 0;" value="RAD.0" oninput="this.setAttribute('value',this.value);this.parentNode.firstElementChild.innerHTML=this.value;">
</div></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>
`;
