z_wizardCode.i_wizard = {};
z_wizardCode.i_wizard.a_documentation = `
This one covers some borderRadius, and then it also give a good way of controlling the outline and it's colour.
`;
z_wizardCode.i_wizard.b_code = `
<div id="coin33088" data-js-name="coin33088" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="0px" data-width="112px" data-height="112px" style="position: absolute; z-index: 100251200; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 0px; width: 112px; height: 112px; outline: none;" data-coin-trip="?" data-flow="0" data-file-include="f_topLeft.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: grey dashed 4px; border-top-left-radius: inherit; border-top-right-radius: inherit; border-bottom-left-radius: 0px; border-bottom-right-radius: 192px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 103;
window.opener.cC = 55;
window.opener.borderRadiusTuner();
} catch {};
"></button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin34597" data-js-name="coin34597" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="272px" data-top="0px" data-width="112px" data-height="112px" style="position: absolute; z-index: 100251300; user-select: none; transform-origin: left top; transform: scale(1); left: 272px; top: 0px; width: 112px; height: 112px; outline: none;" data-coin-trip="?" data-flow="1" data-file-include="g_topRight.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: grey dashed 4px; border-top-left-radius: inherit; border-top-right-radius: inherit; border-bottom-left-radius: 192px; border-bottom-right-radius: inherit;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 105;
window.opener.cC = 57;
window.opener.borderRadiusTuner();
} catch {};
"></button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin25032" data-js-name="coin25032" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="128px" data-top="8px" data-width="60px" data-height="84px" style="position: absolute; z-index: 100251400; user-select: none; transform-origin: left top; transform: scale(1); left: 128px; top: 8px; width: 60px; height: 84px; outline: none;" data-coin-trip="?" data-file-include="k_radiusMinus.html" data-flow="2"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0deg" data-rotate-y="0deg" data-rotate-z="0deg" data-translate-z="0px" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; transform: perspective(1536px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) translateZ(0px); outline: grey solid 4px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 109;
window.opener.cC = 45;
window.opener.borderRadiusTuner();
} catch {};
">-</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin29368" data-js-name="coin29368" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="200px" data-top="8px" data-width="60px" data-height="84px" style="position: absolute; z-index: 100251500; user-select: none; transform-origin: left top; transform: scale(1); left: 200px; top: 8px; width: 60px; height: 84px; outline: none;" data-coin-trip="?" data-file-include="j_radiusPlus.html" data-flow="3"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: grey solid 4px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 107;
window.opener.cC = 43;
window.opener.borderRadiusTuner();
} catch {};
">+</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin68418" data-js-name="coin68418" data-drag-pull="backgroundColor" data-parent="" data-children="" data-finished-outline="none" data-outline-colour="grey" style="position: absolute; transform-origin: left top; transform: scale(1); z-index: 100251600; user-select: none; left: 64px; top: 104px; width: 256px; height: 48px; outline: none;" data-left="64px" data-top="104px" data-width="256px" data-height="48px" data-scale="1" data-angle="0" data-coin-trip="?" data-flow="4"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0); font-size: 32px; text-shadow: rgba(127, 127, 127, 0.75) 1px 1px 1px;"><u>Outline Colour</u></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin62046" data-js-name="coin62046" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="16px" data-top="144px" data-width="96px" data-height="96px" style="position: absolute; z-index: 100251700; user-select: none; transform-origin: left top; transform: scale(1); left: 16px; top: 144px; width: 96px; height: 96px; outline: none;" data-coin-trip="?" data-flow="5" data-file-include="a_numpadSlash.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: grey solid 5px; border-radius: 192px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; font-size: 48px; text-shadow: rgba(127, 127, 127, 0.75) 1.5px 1.5px 1.5px;"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 111;
window.opener.cC = 47;
window.opener.borderRadiusTuner();
} catch {};
">/</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin60512" data-js-name="coin60512" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="272px" data-top="144px" data-width="96px" data-height="96px" style="position: absolute; z-index: 100251800; user-select: none; transform-origin: left top; transform: scale(1); left: 272px; top: 144px; width: 96px; height: 96px; outline: none;" data-coin-trip="?" data-flow="6" data-file-include="b_numpadStar.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: grey solid 5px; border-radius: 192px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; font-size: 48px; text-shadow: rgba(127, 127, 127, 0.75) 1.5px 1.5px 1.5px;"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 106;
window.opener.cC = 42;
window.opener.borderRadiusTuner();
} catch {};
">*</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin69768" data-js-name="coin69768" data-drag-pull="main.style.outlineColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="128px" data-top="176px" data-width="128px" data-height="64px" style="position: absolute; z-index: 100251900; user-select: none; transform-origin: left top; transform: scale(1); left: 128px; top: 176px; width: 128px; height: 64px; outline: none;" data-coin-trip="?" data-flow="7" data-file-include="e_outlineColour.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: rgb(255, 0, 0) solid 5px; border-radius: inherit;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><input type="color" style="width: 100%; height: 100%; margin: 0; padding: 0; border: none;" oninput="
this.parentNode.parentNode.parentNode.dataset.dragPull='main.style.outlineColor';
this.parentNode.parentNode.style.outlineColor=this.value;
try {
window.opener.coinFocus.main.style.outlineColor=this.value;
window.opener.coinFocus.dataset.outlineColour=this.value;
} catch {};
">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin38049" data-js-name="coin38049" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="272px" data-width="112px" data-height="112px" style="position: absolute; z-index: 100252000; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 272px; width: 112px; height: 112px; outline: none;" data-coin-trip="?" data-flow="8" data-file-include="h_bottomLeft.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: grey dashed 4px; border-top-left-radius: inherit; border-top-right-radius: 192px; border-bottom-left-radius: 0px; border-bottom-right-radius: inherit;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 97;
window.opener.cC = 49;
window.opener.borderRadiusTuner();
} catch {};
"></button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin63967" data-js-name="coin63967" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="128px" data-top="272px" data-width="56px" data-height="112px" style="position: absolute; z-index: 100252100; user-select: none; transform-origin: left top; transform: scale(1); left: 128px; top: 272px; width: 56px; height: 112px; outline: none;" data-coin-trip="?" data-flow="9" data-file-include="c_numpadZero.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: grey solid 5px; border-radius: 192px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 96;
window.opener.cC = 48;
window.opener.borderRadiusTuner();
} catch {};
">0</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin65726" data-js-name="coin65726" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="200px" data-top="272px" data-width="56px" data-height="112px" style="position: absolute; z-index: 100252200; user-select: none; transform-origin: left top; transform: scale(1); left: 200px; top: 272px; width: 56px; height: 112px; outline: none;" data-coin-trip="?" data-flow="10" data-file-include="d_numpadDot.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: grey solid 5px; border-radius: 192px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 110;
window.opener.cC = 46;
window.opener.borderRadiusTuner();
} catch {};
">.</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin36115" data-js-name="coin36115" data-drag-pull="div.style.textIndent,div.style.fontSize,div.style.lineHeight,div.style.wordSpacing,div.style.letterSpacing,div.style.textAlign" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="272px" data-top="272px" data-width="112px" data-height="112px" style="position: absolute; z-index: 100252300; user-select: none; transform-origin: left top; transform: scale(1); left: 272px; top: 272px; width: 112px; height: 112px; outline: none;" data-coin-trip="?" data-flow="11" data-file-include="i_bottomRight.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline: grey dashed 4px; border-top-left-radius: 192px; border-top-right-radius: inherit; border-bottom-left-radius: 0px; border-bottom-right-radius: inherit;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.styleKey = 'r';
window.opener.kC = 99;
window.opener.cC = 51;
window.opener.borderRadiusTuner();
} catch {};
"></button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>
`;
