

ui.pageDescription.input         = function() { topLayer[topLayer.a_currentLayer].d_description = ui.pageDescription.ref.value; };

ui.projectName.input             = function() { topLayer.aa_project_name = ui.projectName.ref.value; };

ui.coin77155.click               = function() { deMinimis(true, null, null, null, null, null, null, event); layerRight(); buzzWord(0,'SAVE',128,'magenta',200,200,25,'top','','',event); };
ui.coin59760.click               = function() { layerLeft();  };
ui.coin64291.click               = function() { layerRight(); };
ui.coin70038.click               = function() { navigator.clipboard.writeText(utilityLayer0.innerHTML); };
ui.coin49592.click               = function() { openProject(); buzzWord(0,'OPEN',128,'magenta',200,200,25,'top','','',event); };
ui.coin54398.click               = function() { saveProject(); buzzWord(0,'SAVE',128,'magenta',200,200,25,'top','','',event); };

ui.coin77671.input               = function() { filename = ui.coin77671.ref.value; topLayer[topLayer.a_currentLayer].filename = filename; };
ui.levelNotes.input              = function() { topLayer[topLayer.a_currentLayer].h_notes = ui.levelNotes.ref.value; };

ui.setLayer1.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("b_layer1"); buzzWord(0,'<sup>1</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer1");  } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("b_layer1" ); } };
ui.setLayer2.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("c_layer2"); buzzWord(0,'<sup>2</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer2");  } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("c_layer2" ); } };
ui.setLayer3.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("d_layer3"); buzzWord(0,'<sup>3</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer3");  } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("d_layer3" ); } };
ui.setLayer4.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("e_layer4"); buzzWord(0,'<sup>4</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer4");  } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("e_layer4" ); } };
ui.setLayer5.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("f_layer5"); buzzWord(0,'<sup>5</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer5");  } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("f_layer5" ); } };
ui.setLayer6.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("g_layer6"); buzzWord(0,'<sup>6</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer6");  } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("g_layer6" ); } };
ui.setLayer7.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("h_layer7"); buzzWord(0,'<sup>7</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer7");  } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("h_layer7" ); } };
ui.setLayer8.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("i_layer8"); buzzWord(0,'<sup>8</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer8");  } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("i_layer8" ); } };
ui.setLayer9.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("j_layer9"); buzzWord(0,'<sup>9</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer9");  } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("j_layer9" ); } };
ui.setLayer10.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("k_layer10");buzzWord(0,'<sup>10</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer10"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("k_layer10"); } };
ui.setLayer11.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("l_layer11");buzzWord(0,'<sup>11</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer11"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("l_layer11"); } };
ui.setLayer12.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("m_layer12");buzzWord(0,'<sup>12</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer12"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("m_layer12"); } };
ui.setLayer13.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("n_layer13");buzzWord(0,'<sup>13</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer13"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("n_layer13"); } };
ui.setLayer14.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("o_layer14");buzzWord(0,'<sup>14</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer14"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("o_layer14"); } };
ui.setLayer15.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("p_layer15");buzzWord(0,'<sup>15</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer15"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("p_layer15"); } };
ui.setLayer16.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("q_layer16");buzzWord(0,'<sup>16</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer16"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("q_layer16"); } };
ui.setLayer17.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("r_layer17");buzzWord(0,'<sup>17</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer17"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("r_layer17"); } };
ui.setLayer18.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("s_layer18");buzzWord(0,'<sup>18</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer18"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("s_layer18"); } };
ui.setLayer19.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("t_layer19");buzzWord(0,'<sup>19</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer19"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("t_layer19"); } };
ui.setLayer20.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("u_layer20");buzzWord(0,'<sup>20</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer20"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("u_layer20"); } };
ui.setLayer21.click              = function() { };
ui.setLayer22.click              = function() { };
ui.setLayer23.click              = function() { };
ui.setLayer24.click              = function() { };
ui.setLayer25.click              = function() { };


ui.LVL1.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("b_layer1" ); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer1" ); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("b_layer1" ); } };
ui.LVL2.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("c_layer2" ); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer2" ); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("c_layer2" ); } };
ui.LVL3.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("d_layer3" ); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer3" ); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("d_layer3" ); } };
ui.LVL4.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("e_layer4" ); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer4" ); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("e_layer4" ); } };
ui.LVL5.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("f_layer5" ); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer5" ); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("f_layer5" ); } };
ui.LVL6.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("g_layer6" ); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer6" ); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("g_layer6" ); } };
ui.LVL7.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("h_layer7" ); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer7" ); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("h_layer7" ); } };
ui.LVL8.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("i_layer8" ); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer8" ); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("i_layer8" ); } };
ui.LVL9.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("j_layer9" ); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer9" ); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("j_layer9" ); } };
ui.LVL10.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("k_layer10"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer10"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("k_layer10"); } };
ui.LVL11.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("l_layer11"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer11"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("l_layer11"); } };
ui.LVL12.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("m_layer12"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer12"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("m_layer12"); } };
ui.LVL13.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("n_layer13"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer13"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("n_layer13"); } };
ui.LVL14.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("o_layer14"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer14"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("o_layer14"); } };
ui.LVL15.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("p_layer15"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer15"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("p_layer15"); } };
ui.LVL16.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("q_layer16"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer16"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("q_layer16"); } };
ui.LVL17.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("r_layer17"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer17"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("r_layer17"); } };
ui.LVL18.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("s_layer18"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer18"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("s_layer18"); } };
ui.LVL19.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("t_layer19"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer19"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("t_layer19"); } };
ui.LVL20.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("u_layer20"); } else if ( event.shiftKey && !event.ctrlKey) { pushState("setLayer20"); } else if (!event.shiftKey &&  event.ctrlKey) { copyStateCode("u_layer20"); } };



