

ui.pageDescription.input         = function() { topLayer[topLayer.a_currentLayer].d_description = ui.pageDescription.ref.value; };

ui.projectName.input             = function() { topLayer.aa_project_name = ui.projectName.ref.value; };

ui.coin77155.click               = function() { deMinimis(true); layerRight(); buzzWord(0,'SAVE',128,'magenta',200,200,25,'top','','',event); };
ui.coin59760.click               = function() { layerLeft();  };
ui.coin64291.click               = function() { layerRight(); };
ui.coin70038.click               = function() { navigator.clipboard.writeText(utilityLayer0.innerHTML); };
ui.coin49592.click               = function() { openProject(); buzzWord(0,'OPEN',128,'magenta',200,200,25,'top','','',event); };
ui.coin54398.click               = function() { saveProject(); buzzWord(0,'SAVE',128,'magenta',200,200,25,'top','','',event); };

ui.coin77671.input               = function() { filename = ui.coin77671.ref.value; topLayer[topLayer.a_currentLayer].filename = filename; };
ui.levelNotes.input              = function() { topLayer[topLayer.a_currentLayer].h_notes = ui.levelNotes.ref.value; };

ui.setLayer1.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("b_layer1"); buzzWord(0,'<sup>1</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.b_layer1.b_content.innerHTML); buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer1"); } };
ui.setLayer2.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("c_layer2"); buzzWord(0,'<sup>2</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.c_layer2.b_content.innerHTML); buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer2"); } };
ui.setLayer3.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("d_layer3"); buzzWord(0,'<sup>3</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.d_layer3.b_content.innerHTML); buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer3"); } };
ui.setLayer4.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("e_layer4"); buzzWord(0,'<sup>4</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.e_layer4.b_content.innerHTML); buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer4"); } };
ui.setLayer5.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("f_layer5"); buzzWord(0,'<sup>5</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.f_layer5.b_content.innerHTML); buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer5"); } };
ui.setLayer6.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("g_layer6"); buzzWord(0,'<sup>6</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.g_layer6.b_content.innerHTML); buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer6"); } };
ui.setLayer7.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("h_layer7"); buzzWord(0,'<sup>7</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.h_layer7.b_content.innerHTML); buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer7"); } };
ui.setLayer8.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("i_layer8"); buzzWord(0,'<sup>8</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.i_layer8.b_content.innerHTML); buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer8"); } };
ui.setLayer9.click               = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("j_layer9"); buzzWord(0,'<sup>9</sup>' ,192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.j_layer9.b_content.innerHTML); buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer9"); } };
ui.setLayer10.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("k_layer10");buzzWord(0,'<sup>10</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.k_layer10.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer10"); } };
ui.setLayer11.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("l_layer11");buzzWord(0,'<sup>11</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.l_layer11.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer11"); } };
ui.setLayer12.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("m_layer12");buzzWord(0,'<sup>12</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.m_layer12.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer12"); } };
ui.setLayer13.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("n_layer13");buzzWord(0,'<sup>13</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.n_layer13.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer13"); } };
ui.setLayer14.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("o_layer14");buzzWord(0,'<sup>14</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.o_layer14.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer14"); } };
ui.setLayer15.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("p_layer15");buzzWord(0,'<sup>15</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.p_layer15.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer15"); } };
ui.setLayer16.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("q_layer16");buzzWord(0,'<sup>16</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.q_layer16.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer16"); } };
ui.setLayer17.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("r_layer17");buzzWord(0,'<sup>17</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.r_layer17.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer17"); } };
ui.setLayer18.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("s_layer18");buzzWord(0,'<sup>18</sup>',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.s_layer18.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);} else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer18"); } };
ui.setLayer19.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("t_layer19");buzzWord(0,'<sup>19</sup',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.t_layer19.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);}  else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer19"); } };
ui.setLayer20.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("u_layer20");buzzWord(0,'<sup>20</sup',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.u_layer20.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);}  else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer20"); } };
ui.setLayer21.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("v_layer21");buzzWord(0,'<sup>21</sup',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.v_layer21.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);}  else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer21"); } };
ui.setLayer22.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("w_layer22");buzzWord(0,'<sup>22</sup',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.w_layer22.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);}  else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer22"); } };
ui.setLayer23.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("x_layer23");buzzWord(0,'<sup>23</sup',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.x_layer23.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);}  else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer23"); } };
ui.setLayer24.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("y_layer24");buzzWord(0,'<sup>24</sup',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.y_layer24.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);}  else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer24"); } };
ui.setLayer25.click              = function() { if (!event.shiftKey && !event.ctrlKey) { changeLayer("z_layer25");buzzWord(0,'<sup>25</sup',192,'magenta',200,200,25,'top','','',event);} else if ( event.shiftKey && !event.ctrlKey) { deMinimis(false,lastFactor,'','','',topLayer.z_layer25.b_content.innerHTML);buzzWord(0,'SAVE',96,'magenta',200,200,25,'top','','',event);}  else if (!event.shiftKey &&  event.ctrlKey) { pushState("setLayer25"); } };

/*

THIS IS SOME PREPARATORY WORK TO COPY A FILE INFORMATION



let nameList = topLayer[layerArray[j]].filename + " =\n[";
for (let i = 0; i < topLayer[layerArray[j]].b_content.children.length; i++) {
nameList += '\n"' + topLayer[layerArray[j]].b_content.children[i].id + '"';
if (i != topLayer[layerArray[j]].b_content.children.length - 1) {
nameList += ',';
}
}
nameList += "\n];";
*/
