function spreadReference(coinPull,coinRef) {


try {
if (coinPull!=null) {
       if (coinRef.name=="q"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.q.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.q.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.q.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="w"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.w.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.w.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.w.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="e"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.e.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.e.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.e.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="r"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.r.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.r.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.r.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="t"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.t.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.t.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.t.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="y"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.y.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.y.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.y.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="u"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.u.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.u.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.u.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="i"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.i.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.i.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.i.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="o"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.o.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.o.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.o.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="p"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.p.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.p.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.p.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="a"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.a.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.a.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.a.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="s"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.s.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.s.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.s.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="d"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.d.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.d.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.d.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="f"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.f.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.f.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.f.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="g"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.g.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.g.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.g.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="h"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.h.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.h.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.h.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="j"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.j.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.j.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.j.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="k"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.k.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.k.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.k.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="l"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.l.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.l.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.l.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="z"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.z.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.z.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.z.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="x"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.x.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.x.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.x.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="c"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.c.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.c.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.c.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="v"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.v.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.v.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.v.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="b"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.b.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.b.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.b.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="n"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.n.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.n.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.n.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="m"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].hold.m.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].hold.m.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].hold.m.value = coinRef.value; window.children[j].readCoins(); } } } 





} else if (coinRef.name=="multiplePasteBuffer"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].multiplePasteBuffer.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].multiplePasteBuffer.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].multiplePasteBuffer.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="sel0PasteBuffer"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].sel0PasteBuffer.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].sel0PasteBuffer.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].sel0PasteBuffer.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="sel1PasteBuffer"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].sel1PasteBuffer.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].sel1PasteBuffer.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].sel1PasteBuffer.value = coinRef.value; window.children[j].readCoins(); } } } 
} else if (coinRef.name=="sel2PasteBuffer"){ coinRef.value = coinPull; if (referenceLock) { for (let j = 0; j < window.parents.length; j++) { if (!window.parents[j].closed) { window.parents[j].sel2PasteBuffer.value = coinRef.value; window.parents[j].readCoins(); } for (let i = 0; i < window.parents[j].children.length; i++) { if (!window.parents[j].children[i].closed) { window.parents[j].children[i].sel2PasteBuffer.value = coinRef.value; window.parents[j].children[i].readCoins(); } } } for (let j = 0; j < window.children.length; j++) { if (!window.children[j].closed) { window.children[j].sel2PasteBuffer.value = coinRef.value; window.children[j].readCoins(); } } } 
}

readCoins();

return (1);
} else {
return (0);
}
} catch {
return (0);
}

}
