findFileList =
`
../a_keyboardFunctions/a_keyboardRouter/a_modeRouter.js
../a_keyboardFunctions/a_keyboardRouter/b_hjklRouter.js
../a_keyboardFunctions/a_keyboardRouter/c_aioNRouter.js
../a_keyboardFunctions/a_keyboardRouter/d_numpadRouter.js
../a_keyboardFunctions/a_keyboardRouter/e_scrollRouter.js
../a_keyboardFunctions/a_keyboardRouter/f_shiftRouter.js
../a_keyboardFunctions/a_keyboardRouter/g_topRowRouter.js
../a_keyboardFunctions/a_keyboardRouter/h_styleTuner/a_styleTuner.js
../a_keyboardFunctions/a_keyboardRouter/h_styleTuner/b_borderRadiusTuner.js
../a_keyboardFunctions/a_keyboardRouter/h_styleTuner/c_boxShadowTuner.js
../a_keyboardFunctions/a_keyboardRouter/h_styleTuner/f_paddingTuner.js
../a_keyboardFunctions/a_keyboardRouter/h_styleTuner/g_alignmentTuner.js
../a_keyboardFunctions/a_keyboardRouter/h_styleTuner/h_fontTuner.js
../a_keyboardFunctions/a_keyboardRouter/i_constructionTuner/a_constructionTuner.js
../a_keyboardFunctions/a_keyboardRouter/i_constructionTuner/b_windowTuner.js
../a_keyboardFunctions/a_keyboardRouter/i_constructionTuner/c_grabTuner.js
../a_keyboardFunctions/a_keyboardRouter/i_constructionTuner/d_edgeTuner.js
../a_keyboardFunctions/a_keyboardRouter/i_constructionTuner/e_duplicateTuner.js
../a_keyboardFunctions/a_keyboardRouter/i_constructionTuner/f_tricolourTuner.js
../a_keyboardFunctions/b_topModeKeys/a_spaceView/a_spaceViewOn.js
../a_keyboardFunctions/b_topModeKeys/a_spaceView/b_spaceViewOff.js
../a_keyboardFunctions/b_topModeKeys/a_spaceView/c_spaceViewToggle.js
../a_keyboardFunctions/b_topModeKeys/a_spaceView/d_spaceViewToggleAndExposeAttributesAsText.js
../a_keyboardFunctions/b_topModeKeys/a_spaceView/e_flipHauptMode.js
../a_keyboardFunctions/b_topModeKeys/a_spaceView/f_removePointerEventsNone.js
../a_keyboardFunctions/b_topModeKeys/a_spaceView/g_restorePointerEventsNone.js
../a_keyboardFunctions/b_topModeKeys/b_modeKeys/a_constructionModeKeys.js
../a_keyboardFunctions/b_topModeKeys/b_modeKeys/b_styleDeclarationModeKeys.js
../a_keyboardFunctions/c_bufferOperations/a_gridArray.js
../a_keyboardFunctions/c_bufferOperations/b_pasteOut.js
../a_keyboardFunctions/c_bufferOperations/c_pasteSingle.js
../a_keyboardFunctions/c_bufferOperations/d_pasteMultiple.js
../a_keyboardFunctions/c_bufferOperations/e_groupPaste.js
../a_keyboardFunctions/c_bufferOperations/f_spreadReference.js
../a_keyboardFunctions/d_miscellaneous/a_writeInfoToFace.js
../a_keyboardFunctions/d_miscellaneous/b_togglePartNames.js
../a_keyboardFunctions/d_miscellaneous/c_externalLink.js
../a_keyboardFunctions/d_miscellaneous/d_promptDownloadLink.js
../a_keyboardFunctions/d_miscellaneous/e_copyFilenameLink.js
../a_keyboardFunctions/d_miscellaneous/e_copyOutgoingHashLink.js
../a_keyboardFunctions/d_miscellaneous/f_finalizeHTMLandOpen.js
../a_keyboardFunctions/d_miscellaneous/g_wrapParts.js
../a_keyboardFunctions/d_miscellaneous/h_unwrapParts.js
../a_keyboardFunctions/d_miscellaneous/h_unwrapPartsAlways.js
../a_keyboardFunctions/d_miscellaneous/i_findFurthestExtent.js
../a_keyboardFunctions/d_miscellaneous/j_wrapDocument.js
../a_keyboardFunctions/d_miscellaneous/k_findLeastExtent.js
../a_keyboardFunctions/d_miscellaneous/l_wrapDocumentWithScreen.js
../a_keyboardFunctions/d_miscellaneous/m_userSelectNone.js
../a_keyboardFunctions/d_miscellaneous/n_flipAnchorZ.js
../a_keyboardFunctions/d_miscellaneous/o_buttonDiv.js
../a_keyboardFunctions/d_miscellaneous/p_overflowMain.js
../a_keyboardFunctions/d_miscellaneous/q_makeItContentEditable.js
../a_keyboardFunctions/d_miscellaneous/r_goFullscreen.js
../a_keyboardFunctions/d_miscellaneous/s_setDragPullFromContext.js
../a_keyboardFunctions/d_miscellaneous/t_wrapPink.js
../a_keyboardFunctions/d_miscellaneous/u_wrapGrey.js
../a_keyboardFunctions/d_miscellaneous/v_wrapBlue.js
../a_keyboardFunctions/d_miscellaneous/w_cutOutImage.js
../a_keyboardFunctions/d_miscellaneous/x_saveInternalImage.js
../a_keyboardFunctions/d_miscellaneous/y_cutImagesAll.js
../a_keyboardFunctions/d_miscellaneous/z_applyImageBack.js
../a_keyboardFunctions/e_saveAndAppend/a_quitSave.js
../a_keyboardFunctions/e_saveAndAppend/b_saveHTMLparticle.js
../a_keyboardFunctions/e_saveAndAppend/c_saveParticlePreparation.js
../a_keyboardFunctions/e_saveAndAppend/d_copyOpenerContents.js
../a_keyboardFunctions/e_saveAndAppend/e_openFile.js
../a_keyboardFunctions/e_saveAndAppend/f_appendFile.js
../a_keyboardFunctions/e_saveAndAppend/g_openImageFile.js
../a_keyboardFunctions/e_saveAndAppend/h_openHTMLinNewWindow.js
../a_keyboardFunctions/e_saveAndAppend/i_saveStartupTutorial.js
../a_keyboardFunctions/e_saveAndAppend/j_saveWithHeaderFooter.js
../a_keyboardFunctions/e_saveAndAppend/k_saveFromHotdog.js
../a_keyboardFunctions/e_saveAndAppend/l_openImageSheet.js
../a_keyboardFunctions/e_saveAndAppend/m_clearImageSheet.js
../a_keyboardFunctions/e_saveAndAppend/n_viewImageSheet.js
../a_keyboardFunctions/f_documentOrder/a_flowManagement/a_reflow.js
../a_keyboardFunctions/f_documentOrder/a_flowManagement/b_reflowGlobal.js
../a_keyboardFunctions/f_documentOrder/a_flowManagement/c_reflowPerTrip.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/a_globalZManagement/a_manageGlobalZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/a_globalZManagement/b_ceilingGlobalZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/a_globalZManagement/c_lowerGlobalZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/a_globalZManagement/d_raiseGlobalZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/a_globalZManagement/e_floorGlobalZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/b_tripartiteZManagement/a_manageTripartiteZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/b_tripartiteZManagement/b_ceilingTripartiteZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/b_tripartiteZManagement/c_lowerTripartiteZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/b_tripartiteZManagement/d_raiseTripartiteZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/b_tripartiteZManagement/e_floorTripartiteZ.js
../a_keyboardFunctions/f_documentOrder/b_zIndexManagement/c_findZextrema/a_findZextrema.js
../a_keyboardFunctions/g_movement/a_alignCenter/a_moveLeftAndCentre.js
../a_keyboardFunctions/g_movement/a_alignCenter/b_moveDownAndCentre.js
../a_keyboardFunctions/g_movement/a_alignCenter/c_moveUpAndCentre.js
../a_keyboardFunctions/g_movement/a_alignCenter/d_moveRightAndCentre.js
../a_keyboardFunctions/g_movement/b_alignEdges/a_moveLeft.js
../a_keyboardFunctions/g_movement/b_alignEdges/b_moveDown.js
../a_keyboardFunctions/g_movement/b_alignEdges/c_moveUp.js
../a_keyboardFunctions/g_movement/b_alignEdges/d_moveRight.js
../a_keyboardFunctions/g_movement/c_moveAll/a_moveAllLeft.js
../a_keyboardFunctions/g_movement/c_moveAll/b_moveAllDown.js
../a_keyboardFunctions/g_movement/c_moveAll/c_moveAllUp.js
../a_keyboardFunctions/g_movement/c_moveAll/d_moveAllRight.js
../a_keyboardFunctions/g_movement/d_explicitEntry/a_explicitEntryForTopAndLeft.js
../a_keyboardFunctions/h_extendEdge/a_extendEdge.js
../a_keyboardFunctions/h_extendEdge/b_halfSize.js
../a_keyboardFunctions/h_extendEdge/c_doubleSize.js
../a_keyboardFunctions/i_tripartiteOperations/a_assignAllColours.js
../a_keyboardFunctions/i_tripartiteOperations/b_swapColours.js
../a_keyboardFunctions/i_tripartiteOperations/c_setCoinTrip.js
../a_keyboardFunctions/i_tripartiteOperations/d_recoverColouration.js
../a_keyboardFunctions/i_tripartiteOperations/e_readCoins.js
../a_keyboardFunctions/j_insertionAndDeletion/a_deletion/a_deleteCoin.js
../a_keyboardFunctions/j_insertionAndDeletion/a_deletion/b_groupDeletion.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/a_insertNew/a_insertNewCoin.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/a_insertNew/b_insertNewDuplicate.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/a_insertNew/c_insertNewImage.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/b_insertDragSelector/a_insertDragIns.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/b_insertDragSelector/b_insertNamedColours.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/b_insertDragSelector/c_insertGrayscale.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/b_insertDragSelector/d_insertFontSizeAndPadding.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/b_insertDragSelector/e_insertFontVarious.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/b_insertDragSelector/f_insertBorderSelector.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/b_insertDragSelector/g_insertBoxShadowSelector.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/b_insertDragSelector/h_otherFontAndTemplates.js
../a_keyboardFunctions/j_insertionAndDeletion/b_insertion/b_insertDragSelector/i_insertSingleTemplates.js
../a_keyboardFunctions/j_insertionAndDeletion/c_guideLayer/a_guideLayer.js
../a_keyboardFunctions/j_insertionAndDeletion/c_guideLayer/b_pullFromGuideLayer.js
../a_keyboardFunctions/k_brickAndStack/a_brickHorizontal.js
../a_keyboardFunctions/k_brickAndStack/b_brickVertical.js
../a_keyboardFunctions/k_brickAndStack/c_stackHorizontal.js
../a_keyboardFunctions/k_brickAndStack/d_stackVertical.js
../a_keyboardFunctions/k_brickAndStack/e_stepStackDiagonal.js
../a_keyboardFunctions/k_brickAndStack/f_stackPoint.js
../a_keyboardFunctions/k_brickAndStack/g_stepStackFlat.js
../a_keyboardFunctions/k_brickAndStack/h_stackVerticalCentre.js
../a_keyboardFunctions/k_brickAndStack/i_stackHorizontalCentre.js
../a_keyboardFunctions/l_styleOperations/a_gridToPadding.js
../a_keyboardFunctions/l_styleOperations/b_gridToBorderRadius.js
../a_keyboardFunctions/l_styleOperations/c_gridToFontSize.js
../a_keyboardFunctions/l_styleOperations/d_gridToOutline.js
../a_keyboardFunctions/l_styleOperations/e_gridToBoxShadow.js
../a_keyboardFunctions/l_styleOperations/f_cycleTextAlignment.js
../a_keyboardFunctions/l_styleOperations/g_cycleFonts.js
../a_keyboardFunctions/l_styleOperations/h_gridToIndent.js
../a_keyboardFunctions/m_manualEntry/a_enterArticleContent.js
../a_keyboardFunctions/m_manualEntry/b_enterCODEnote.js
../a_keyboardFunctions/m_manualEntry/c_enterPHPref.js
../a_keyboardFunctions/m_manualEntry/d_jsNameAndNote.js
../a_keyboardFunctions/m_manualEntry/e_enterBackgroundColour.js
../a_keyboardFunctions/m_manualEntry/f_enterForegroundColour.js
../a_keyboardFunctions/m_manualEntry/g_enterOutlineColour.js
../a_keyboardFunctions/m_manualEntry/h_enterPageEchelon.js
../a_keyboardFunctions/m_manualEntry/i_setSequentialIds.js
../a_keyboardFunctions/m_manualEntry/j_customPrompt.js
../a_keyboardFunctions/m_manualEntry/k_enterImageAltText.js
../a_keyboardFunctions/m_manualEntry/l_enterClassNames.js
../a_keyboardFunctions/n_window/a_windowEdge.js
../a_keyboardFunctions/n_window/b_openTextareaInNewWindow.js
../a_keyboardFunctions/o_rotationAndScale/a_innerRotation/a_innerRotation.js
../a_keyboardFunctions/o_rotationAndScale/a_innerRotation/b_innerRotationMin.js
../a_keyboardFunctions/o_rotationAndScale/a_innerRotation/c_innerRotationCan.js
../a_keyboardFunctions/o_rotationAndScale/b_3dTransform/a_rotateUnder.js
../a_keyboardFunctions/o_rotationAndScale/b_3dTransform/b_rotateOver.js
../a_keyboardFunctions/o_rotationAndScale/b_3dTransform/c_rotateLeft.js
../a_keyboardFunctions/o_rotationAndScale/b_3dTransform/d_rotateRight.js
../a_keyboardFunctions/o_rotationAndScale/b_3dTransform/e_rotateZleft.js
../a_keyboardFunctions/o_rotationAndScale/b_3dTransform/f_rotateZright.js
../a_keyboardFunctions/o_rotationAndScale/b_3dTransform/g_clearRotation.js
../a_keyboardFunctions/o_rotationAndScale/c_outerScale/a_outerScaleUp.js
../a_keyboardFunctions/o_rotationAndScale/c_outerScale/b_outerScaleDown.js
../a_keyboardFunctions/o_rotationAndScale/c_outerScale/c_resetScale.js
../a_keyboardFunctions/p_F1menu/a_helpMenu.js
../a_keyboardFunctions/q_notificationsSystem/a_noteCoin.js
../a_keyboardFunctions/q_notificationsSystem/b_HJKLnoteCoin.js
../a_keyboardFunctions/q_notificationsSystem/c_noteStyle.js
../a_keyboardFunctions/r_topLayerManager/a_makeTopLayer.js
../a_keyboardFunctions/r_topLayerManager/b_recoverCoinFocus.js
../a_keyboardFunctions/r_topLayerManager/c_layerLeft.js
../a_keyboardFunctions/r_topLayerManager/d_layerRight.js
../a_keyboardFunctions/s_interfaceLayer/a_toggleInterfaceLayer.js
../a_keyboardFunctions/s_interfaceLayer/b_enterWizardMaster.js
../a_keyboardFunctions/s_interfaceLayer/c_toggleInterfaceShelf.js
../a_keyboardFunctions/s_interfaceLayer/d_setDefaultTemplate.js
../a_keyboardFunctions/t_wizards/a_wizarda.js
../a_keyboardFunctions/t_wizards/b_wizardb.js
../a_keyboardFunctions/t_wizards/c_wizardc.js
../a_keyboardFunctions/t_wizards/d_wizardd.js
../a_keyboardFunctions/t_wizards/e_wizarde.js
../a_keyboardFunctions/t_wizards/f_wizardf.js
../a_keyboardFunctions/t_wizards/g_wizardg.js
../a_keyboardFunctions/t_wizards/h_wizardh.js
../a_keyboardFunctions/t_wizards/i_wizardi.js
../a_keyboardFunctions/t_wizards/j_wizardj.js
../a_keyboardFunctions/t_wizards/k_wizardk.js
../a_keyboardFunctions/t_wizards/l_wizardl.js
../a_keyboardFunctions/t_wizards/m_wizardm.js
../a_keyboardFunctions/t_wizards/n_wizardn.js
../a_keyboardFunctions/t_wizards/o_wizardo.js
../a_keyboardFunctions/t_wizards/p_wizardp.js
../a_keyboardFunctions/t_wizards/q_wizardq.js
../a_keyboardFunctions/t_wizards/r_wizardr.js
../a_keyboardFunctions/t_wizards/s_wizards.js
../a_keyboardFunctions/t_wizards/t_wizardt.js
../a_keyboardFunctions/t_wizards/u_wizardu.js
../a_keyboardFunctions/t_wizards/v_wizardv.js
../a_keyboardFunctions/t_wizards/w_wizardw.js
../a_keyboardFunctions/t_wizards/x_wizardx.js
../a_keyboardFunctions/t_wizards/y_wizardy.js
../a_keyboardFunctions/t_wizards/z_wizardz.js
../a_keyboardFunctions/u_localView/a_toggleLocalView.js
../a_keyboardFunctions/u_localView/b_cycleNextLocalView.js
../a_keyboardFunctions/u_localView/c_cyclePreviousLocalView.js
../a_keyboardFunctions/v_cleanConversion/a_buttonizer.js
../a_keyboardFunctions/v_cleanConversion/b_copyToClipboard.js
../a_keyboardFunctions/w_projectLevel/a_saveProject.js
../a_keyboardFunctions/w_projectLevel/b_openProject.js
../b_mouseFunctions/a_enterNewPartFromMouseInput.js
../b_mouseFunctions/b_mouseGiveFocus.js
../b_mouseFunctions/c_mousePlaceCursor.js
../c_focusManagement/a_spatialCursor/a_coinToCursor.js
../c_focusManagement/a_spatialCursor/b_cursorToCoin.js
../c_focusManagement/a_spatialCursor/c_cursorToEnd.js
../c_focusManagement/a_spatialCursor/d_cursorToHome.js
../c_focusManagement/a_spatialCursor/e_coinCentreToCursor.js
../c_focusManagement/a_spatialCursor/f_cursorToCoinCentre.js
../c_focusManagement/a_spatialCursor/g_cursorToCoinTopLeft.js
../c_focusManagement/a_spatialCursor/h_cursorToCoinTopRight.js
../c_focusManagement/a_spatialCursor/i_cursorToCoinBottomLeft.js
../c_focusManagement/a_spatialCursor/j_cursorToCoinBottomRight.js
../c_focusManagement/a_spatialCursor/k_cursorToWindowCentre.js
../c_focusManagement/a_spatialCursor/l_cursorMoveLeft.js
../c_focusManagement/a_spatialCursor/m_cursorMoveRight.js
../c_focusManagement/a_spatialCursor/n_cursorMoveUp.js
../c_focusManagement/a_spatialCursor/o_cursorMoveDown.js
../c_focusManagement/a_spatialCursor/p_cursorToCoinTopCentre.js
../c_focusManagement/a_spatialCursor/q_cursorToCoinLeftCentre.js
../c_focusManagement/a_spatialCursor/r_cursorToCoinRightCentre.js
../c_focusManagement/a_spatialCursor/s_cursorToCoinBottomCentre.js
../c_focusManagement/b_focus/a_focusFlip.js
../c_focusManagement/b_focus/b_focusPrevious.js
../c_focusManagement/b_focus/c_focusNext.js
../c_focusManagement/b_focus/d_focusFirst.js
../c_focusManagement/b_focus/e_focusLast.js
../c_focusManagement/b_focus/f_focusNextColour.js
../c_focusManagement/b_focus/g_focusSet.js
../c_focusManagement/c_scanAndSet/a_scanForCoin.js
../c_focusManagement/c_scanAndSet/b_setCoinTripColouration.js
`;

