function setDefaultTemplate() {
if (coinFocus!=null) {
template.default.background         = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.background      ;
template.default.backgroundColor    = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.backgroundColor ;
template.default.color              = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.color           ;
template.default.textShadow         = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textShadow      ;
template.default.textAlign          = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textAlign       ;
template.default.textIndent         = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textIndent      ;
template.default.fontSize           = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontSize        ;
template.default.fontStyle          = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontStyle       ;
template.default.fontWeight         = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontWeight      ;
template.default.fontVariant        = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontVariant     ;
template.default.fontFamily         = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontFamily      ;
template.default.lineHeight         = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.lineHeight      ;
template.default.wordSpacing        = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.wordSpacing     ;
template.default.letterSpacing      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.letterSpacing   ;
template.default.textTransform      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textTransform   ;
template.default.direction          = coinFocus.lastElementChild.lastElementChild.previousElementSibling.direction             ;
template.default.opacity            = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.opacity         ;
template.default.paddingLeft        = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingLeft     ;
template.default.paddingRight       = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingRight    ;
template.default.paddingTop         = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingTop      ;
template.default.paddingBottom      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingBottom   ;

template.defaultIMG.background      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.background      ;
template.defaultIMG.backgroundColor = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.backgroundColor ;
template.defaultIMG.color           = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.color           ;
template.defaultIMG.textShadow      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textShadow      ;
template.defaultIMG.textAlign       = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textAlign       ;
template.defaultIMG.textIndent      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textIndent      ;
template.defaultIMG.fontSize        = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontSize        ;
template.defaultIMG.fontStyle       = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontStyle       ;
template.defaultIMG.fontWeight      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontWeight      ;
template.defaultIMG.fontVariant     = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontVariant     ;
template.defaultIMG.fontFamily      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontFamily      ;
template.defaultIMG.lineHeight      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.lineHeight      ;
template.defaultIMG.wordSpacing     = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.wordSpacing     ;
template.defaultIMG.letterSpacing   = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.letterSpacing   ;
template.defaultIMG.textTransform   = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textTransform   ;
template.defaultIMG.direction       = coinFocus.lastElementChild.lastElementChild.previousElementSibling.direction             ;
template.defaultIMG.opacity         = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.opacity         ;
template.defaultIMG.paddingLeft     = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingLeft     ;
template.defaultIMG.paddingRight    = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingRight    ;
template.defaultIMG.paddingTop      = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingTop      ;
template.defaultIMG.paddingBottom   = coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingBottom   ;

localStorage.setItem("template.default.background",          coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.background     );  
localStorage.setItem("template.default.backgroundColor",     coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.backgroundColor);
localStorage.setItem("template.default.color",               coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.color          );  
localStorage.setItem("template.default.textShadow",          coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textShadow     );  
localStorage.setItem("template.default.textAlign",           coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textAlign      );  
localStorage.setItem("template.default.textIndent",          coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textIndent     );  
localStorage.setItem("template.default.fontSize",            coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontSize       );  
localStorage.setItem("template.default.fontStyle",           coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontStyle      );  
localStorage.setItem("template.default.fontWeight",          coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontWeight     );  
localStorage.setItem("template.default.fontVariant",         coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontVariant    );  
localStorage.setItem("template.default.fontFamily",          coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontFamily     );  
localStorage.setItem("template.default.lineHeight",          coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.lineHeight     );  
localStorage.setItem("template.default.wordSpacing",         coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.wordSpacing    );  
localStorage.setItem("template.default.letterSpacing",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.letterSpacing  );  
localStorage.setItem("template.default.textTransform",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textTransform  );  
localStorage.setItem("template.default.direction",           coinFocus.lastElementChild.lastElementChild.previousElementSibling.direction            );  
localStorage.setItem("template.default.opacity",             coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.opacity        );  
localStorage.setItem("template.default.paddingLeft",         coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingLeft    );  
localStorage.setItem("template.default.paddingRight",        coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingRight   );  
localStorage.setItem("template.default.paddingTop",          coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingTop     );  
localStorage.setItem("template.default.paddingBottom",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingBottom  );  

localStorage.setItem("template.defaultIMG.background",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.background     );  
localStorage.setItem("template.defaultIMG.backgroundColor",  coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.backgroundColor);
localStorage.setItem("template.defaultIMG.color",            coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.color          );  
localStorage.setItem("template.defaultIMG.textShadow",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textShadow     );  
localStorage.setItem("template.defaultIMG.textAlign",        coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textAlign      );  
localStorage.setItem("template.defaultIMG.textIndent",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textIndent     );  
localStorage.setItem("template.defaultIMG.fontSize",         coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontSize       );  
localStorage.setItem("template.defaultIMG.fontStyle",        coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontStyle      );  
localStorage.setItem("template.defaultIMG.fontWeight",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontWeight     );  
localStorage.setItem("template.defaultIMG.fontVariant",      coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontVariant    );  
localStorage.setItem("template.defaultIMG.fontFamily",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.fontFamily     );  
localStorage.setItem("template.defaultIMG.lineHeight",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.lineHeight     );  
localStorage.setItem("template.defaultIMG.wordSpacing",      coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.wordSpacing    );  
localStorage.setItem("template.defaultIMG.letterSpacing",    coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.letterSpacing  );  
localStorage.setItem("template.defaultIMG.textTransform",    coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.textTransform  );  
localStorage.setItem("template.defaultIMG.direction",        coinFocus.lastElementChild.lastElementChild.previousElementSibling.direction            );  
localStorage.setItem("template.defaultIMG.opacity",          coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.opacity        );  
localStorage.setItem("template.defaultIMG.paddingLeft",      coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingLeft    );  
localStorage.setItem("template.defaultIMG.paddingRight",     coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingRight   );  
localStorage.setItem("template.defaultIMG.paddingTop",       coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingTop     );  
localStorage.setItem("template.defaultIMG.paddingBottom",    coinFocus.lastElementChild.lastElementChild.previousElementSibling.style.paddingBottom  );  
}
}

