function popInsert(idPrefix,popString) {
insertNewCoin([null,78,78,0,0,0]);
coinFocus.style.left     = window.scrollX + 'px';
coinFocus.dataset.left   = window.scrollX + 'px';
coinFocus.style.top      = window.scrollY + 'px';
coinFocus.dataset.top    = window.scrollY + 'px';
coinFocus.style.width    = '500px';
coinFocus.dataset.width  = '500px';
coinFocus.style.height   = '500px';
coinFocus.dataset.height = '500px';
coinFocus.dataset.notes  = `{
"initialDisplay" : "none",
"notes" : "Written notes.",
"YAML"  : "Coded instructions",
"data"  : "Additional JSON"
}`;
coinFocus.id = coinFocus.id.replace(/coin/g, idPrefix);
coinFocus.name = idPrefix;
coinFocus.lastElementChild.lastElementChild.previousElementSibling.innerHTML = popString;
}

/* GIVE MILDLY DIFFERENT APPEARANCE FOR ORGANIZATIONAL PURPOSES */

function popStyle1() { popInsert("style",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAC9JREFUCJljYIUDBlZuGAAzgUJQJpgHZkKUsGJlItRimsANN4EbjwmsaLahmwAEAOcnBbX5pZIzAAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="styleBrick" oninput="this.nextElementSibling.innerHTML = this.value;" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: transparent;"></textarea><style></style></div>`); }
function popStyle2() { popInsert("style",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAC9JREFUCJljYIUDBlZuGAAzgUJQJpgHZkKUsGJlItRimsANN4EbjwmsaLahmwAEAOcnBbX5pZIzAAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="styleBrick" oninput="this.nextElementSibling.innerHTML = this.value;" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea><style></style></div>`); }
function popStyle3() { popInsert("style",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAC9JREFUCJljYIUDBlZuGAAzgUJQJpgHZkKUsGJlItRimsANN4EbjwmsaLahmwAEAOcnBbX5pZIzAAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="styleBrick" oninput="this.nextElementSibling.innerHTML = this.value;" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea><style></style></div>`); }
function popStyle4() { popInsert("style",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAC9JREFUCJlj4IEDBh5uGAAzgUJQJpgHZkKU8GBlItRimsANN4Ebjwk8aLahmwAEAHGSBxOB+ZD4AAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="styleBrick" oninput="this.nextElementSibling.innerHTML = this.value;" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea><style></style></div>`); }
function popStyle5() { popInsert("style",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAC9JREFUCJljYIYDBmZuGAAzgUJQJpgHZkKUMGNlItRimsANN4EbjwnMaLahmwAEAL+fBVFLRhH4AAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="styleBrick" oninput="this.nextElementSibling.innerHTML = this.value;" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea><style></style></div>`); }
function popStyle6() { popInsert("style",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAC9JREFUCJlj4IUDBl5uGAAzgUJQJpgHZkKU8GJlItRimsANN4Ebjwm8aLahmwAEAIVWB0XOskw/AAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="styleBrick" oninput="this.nextElementSibling.innerHTML = this.value;" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea><style></style></div>`); }

function popJSON1() { popInsert("json",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAADVJREFUCJljYIUDBm44ADKhgtwQUVaoKCoTzMZkgthww1jRmaysMCYrQhSdCTUB7AIkw7i5AQGaBgMf8zbwAAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="jsonBrick" oninput="try { this.parentNode.parentNode.parentNode.parentNode.dataset.json = JSON.stringify(JSON.parse(this.value)); this.style.backgroundColor = 'rgba(255,255,255,0.4)'; } catch { this.parentNode.parentNode.parentNode.parentNode.dataset.json = this.value; this.style.backgroundColor = 'rgba(255,240,240,0.4)'; };" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.4);"></textarea></div>`); }
function popJSON2() { popInsert("json",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAADVJREFUCJljYIQDBm44ADKhgtwQUUaoKCoTzMZkgthwwxjRmYyMMCYjQhSdCTUB7AIkw7i5AcQTBW+B4oc7AAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="jsonBrick" oninput="try { this.parentNode.parentNode.parentNode.parentNode.dataset.json = JSON.stringify(JSON.parse(this.value)); this.style.backgroundColor = 'rgba(255,255,255,0.8)'; } catch { this.parentNode.parentNode.parentNode.parentNode.dataset.json = this.value; this.style.backgroundColor = 'rgba(255,240,240,0.8)'; };" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea></div>`); }
function popJSON3() { popInsert("json",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAADVJREFUCJlj4IMDBm44ADKhgtwQUT6oKCoTzMZkgthww/jQmXx8MCYfQhSdCTUB7AIkw7i5AYvoB1AQ7TT/AAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="jsonBrick" oninput="try { this.parentNode.parentNode.parentNode.parentNode.dataset.json = JSON.stringify(JSON.parse(this.value)); this.style.backgroundColor = 'rgba(255,255,255,0.8)'; } catch { this.parentNode.parentNode.parentNode.parentNode.dataset.json = this.value; this.style.backgroundColor = 'rgba(255,240,240,0.8)'; };" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea></div>`); }
function popJSON4() { popInsert("json",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAADVJREFUCJlj4IEDBm44ADKhgtwQUR6oKCoTzMZkgthww3jQmTw8MCYPQhSdCTUB7AIkw7i5AW0sBwZLyALGAAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="jsonBrick" oninput="try { this.parentNode.parentNode.parentNode.parentNode.dataset.json = JSON.stringify(JSON.parse(this.value)); this.style.backgroundColor = 'rgba(255,255,255,0.8)'; } catch { this.parentNode.parentNode.parentNode.parentNode.dataset.json = this.value; this.style.backgroundColor = 'rgba(255,240,240,0.8)'; };" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea></div>`); }
function popJSON5() { popInsert("json",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAADVJREFUCJljYIYDBm44ADKhgtwQUWaoKCoTzMZkgthww5jRmczMMCYzQhSdCTUB7AIkw7i5AeLPBblTBy7sAAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="jsonBrick" oninput="try { this.parentNode.parentNode.parentNode.parentNode.dataset.json = JSON.stringify(JSON.parse(this.value)); this.style.backgroundColor = 'rgba(255,255,255,0.8)'; } catch { this.parentNode.parentNode.parentNode.parentNode.dataset.json = this.value; this.style.backgroundColor = 'rgba(255,240,240,0.8)'; };" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea></div>`); }
function popJSON6() { popInsert("json",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAQCAMAAAAYoR5yAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAADVJREFUCJlj4IUDBm44ADKhgtwQUV6oKCoTzMZkgthww3jRmby8MCYvQhSdCTUB7AIkw7i5AXyKByuZCYzaAAAAAElFTkSuQmCC'); background-size: 20px 32px;"><textarea name="jsonBrick" oninput="try { this.parentNode.parentNode.parentNode.parentNode.dataset.json = JSON.stringify(JSON.parse(this.value)); this.style.backgroundColor = 'rgba(255,255,255,0.8)'; } catch { this.parentNode.parentNode.parentNode.parentNode.dataset.json = this.value; this.style.backgroundColor = 'rgba(255,240,240,0.8)'; };" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea></div>`); }

function popScript() { popInsert("addScript",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAMAAADz0U65AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAACdJREFUCJkty6ENADAQA7ELCcn++36lHjMxTdJtTDH18EUVUUTh7gE2SAGBxTK1ygAAAABJRU5ErkJggg=='); background-size: 20px 32px;"><textarea name="jsonBrick" oninput="this.parentNode.parentNode.parentNode.parentNode.dataset.addScript = this.value;" style="width: 100%; height: 100%; padding: 0px; margin: 0px; border: 0px; resize:none; font-size: inherit; background-color: rgba(255,255,255,0.8);"></textarea></div>`); }

function popAccumulator(string) { popInsert("accumulator",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACMAAAAQCAMAAACr6TZoAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAFhJREFUKJGtkAsOwCAIQ2nvf+gtunXUT0jMSJRqHgoNACxW/MWwjvbOHcAjujQV3wVTtk2Mskgp9QMak5X6sQ+OGeAdbMXk845p1Wnu1Vwjs/PHPZp9Zh0X6wEDqXTVJVMAAAAASUVORK5CYII='); background-size: 35px 16px;"><button style="position: absolute; left: 0px; top: 0px; width: 100%; height: 100%; font-size: 48px; font-family: dckimPixelMono; color: white; background-color: rgba(0,255,0,0.5);" onclick="console.log(JSON.parse(this.parentNode.parentNode.parentNode.parentNode.dataset.accumulator));">console.log</button></div>`); coinFocus.dataset.accumulator = string; topLayer.programStateAccumulator = []; }

function popGroup(string) { popInsert("group",`<div style="width: 100%; height:100%; padding: 0px; margin: 0px; border: 0px; font-size: inherit; background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACMAAAAQCAMAAACr6TZoAAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAE5JREFUKJFjYCQMGNgJAwZqmUOkGpB5KBSQADFgIgwQPjs7XByDJEMNIzaVqGoY0U1Ddg+Yg90cJDcz4rILQw0WNyOHD9w1aKFEQjgTAgC9wQtbD08BiAAAAABJRU5ErkJggg=='); background-size: 35px 16px;"></div>`); coinFocus.dataset.group = string; }