z_wizardCode.j_wizard = {};
z_wizardCode.j_wizard.a_documentation = `
This handles some box-shadow stuff... Though it doesn't handle a direct input for the colour of the box shadow. It still relies on the tint array... Oops.
`;
z_wizardCode.j_wizard.b_code = `
<div id="coin41254" data-js-name="coin41254" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="0px" data-width="64px" data-height="64px" style="position: absolute; z-index: 100250500; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 0px; width: 64px; height: 64px; outline: none;" data-coin-trip="?" data-file-include="d_topLeft.html" data-flow="0"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; margin: 0px; padding: 0px; border: none;" onclick="
try {
window.opener.boxShadowTop  = '-';
window.opener.boxShadowLeft = '-';
window.opener.styleKey = 'u';
window.opener.kC = 0;
window.opener.cC = 0;
window.opener.boxShadowTuner();
} catch {};
">7</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin71679" data-js-name="coin71679" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="64px" data-top="0px" data-width="256px" data-height="64px" style="position: absolute; z-index: 100250800; user-select: none; transform-origin: left top; transform: scale(1); left: 64px; top: 0px; width: 256px; height: 64px; outline: none;" data-coin-trip="?" data-flow="1"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0); font-size: 48px; text-shadow: rgba(0, 0, 0, 0.5) 0.01em 0.01em 2.025px;"><u>box-shadow</u></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin42645" data-js-name="coin42645" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="320px" data-top="0px" data-width="64px" data-height="64px" style="position: absolute; z-index: 100251400; user-select: none; transform-origin: left top; transform: scale(1); left: 320px; top: 0px; width: 64px; height: 64px; outline: none;" data-coin-trip="?" data-file-include="e_topRight.html" data-flow="2"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; margin: 0px; padding: 0px; border: none;" onclick="
try {
window.opener.boxShadowTop  = ' ';
window.opener.boxShadowLeft = '-';
window.opener.styleKey = 'u';
window.opener.kC = 0;
window.opener.cC = 0;
window.opener.boxShadowTuner();
} catch {};
">9</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin83008" data-js-name="coin83008" data-drag-pull="backgroundColor" data-parent="" data-children="coin84759" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="64px" data-width="64px" data-height="256px" style="position: absolute; z-index: 100251500; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 64px; width: 64px; height: 256px; outline: none;" data-coin-trip="?" data-file-include="i_tintBackward.html" data-flow="3"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; margin: 0px; padding: 0px; border: none;" onclick="
try {
window.opener.styleKey = 'u';
window.opener.kC = 102;
window.opener.cC = 54;
window.opener.boxShadowTuner();
} catch {};
"></button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin30196" data-js-name="coin30196" data-parent="coin15146" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="undefined" data-width="256px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251600; user-select: none; left: 64px; top: 64px; width: 256px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="64px" data-top="64px" data-coin-trip="?" data-flow="4"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0);">blur</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin84759" data-js-name="coin84759" data-parent="coin83008" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="h_tintForward.html" data-width="64px" data-height="256px" data-scale="1" style="position: absolute; z-index: 100251700; user-select: none; left: 320px; top: 64px; width: 64px; height: 256px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="320px" data-top="64px" data-coin-trip="?" data-flow="5"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; margin: 0px; padding: 0px; border: none;" onclick="
try {
window.opener.styleKey = 'u';
window.opener.kC = 100;
window.opener.cC = 52;
window.opener.boxShadowTuner();
} catch {};
"></button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin45802" data-js-name="coin45802" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="64px" data-top="96px" data-width="256px" data-height="48px" style="position: absolute; z-index: 100251800; user-select: none; transform-origin: left top; transform: scale(1); left: 64px; top: 96px; width: 256px; height: 48px; outline: none;" data-coin-trip="?" data-file-include="j_boxShadowBlur.html" data-flow="6" data-lock-e="false"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0deg" data-rotate-y="0deg" data-rotate-z="0deg" data-translate-z="0px" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px; transform: perspective(1536px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) translateZ(0px);"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);" contenteditable="true"><input type="range" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" min="0" max="48" step="0.05" oninput="
try {
window.opener.boxShadowBlur = this.value;
window.opener.styleKey = 'u';
window.opener.kC = 0;
window.opener.cC = 0;
window.opener.boxShadowTuner();
} catch {};
">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin40151" data-js-name="coin40151" data-parent="coin15146" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="undefined" data-width="256px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251900; user-select: none; left: 64px; top: 144px; width: 256px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="64px" data-top="144px" data-coin-trip="?" data-flow="7"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0);">distance</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin38707" data-js-name="coin38707" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="64px" data-top="176px" data-width="256px" data-height="48px" style="position: absolute; z-index: 100252000; user-select: none; transform-origin: left top; transform: scale(1); left: 64px; top: 176px; width: 256px; height: 48px; outline: none;" data-coin-trip="?" data-file-include="a_boxShadowSize.html" data-flow="8"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><input type="range" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" min="0" max="200" step="0.5" oninput="
try {
window.opener.boxShadowSize = this.value;
window.opener.styleKey = 'u';
window.opener.kC = 0;
window.opener.cC = 0;
window.opener.boxShadowTuner();
} catch {};
">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin68990" data-js-name="coin68990" data-parent="coin15146" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="undefined" data-width="256px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100252100; user-select: none; left: 64px; top: 224px; width: 256px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="64px" data-top="224px" data-coin-trip="?" data-flow="9"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0);">angle</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin23886" data-js-name="coin23886" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="64px" data-top="256px" data-width="256px" data-height="48px" style="position: absolute; z-index: 100252200; user-select: none; transform-origin: left top; transform: scale(1); left: 64px; top: 256px; width: 256px; height: 48px; outline: none;" data-coin-trip="?" data-file-include="b_boxShadowFactor.html" data-flow="10"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><input type="range" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" min="0" max="1" step="0.0625" oninput="
try {
window.opener.boxShadowFactor = this.value;
window.opener.styleKey = 'u';
window.opener.kC = 0;
window.opener.cC = 0;
window.opener.boxShadowTuner();
} catch {};
">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin15146" data-js-name="coin15146" data-drag-pull="backgroundColor" data-parent="" data-children="coin30196,coin40151,coin68990" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="64px" data-top="304px" data-width="256px" data-height="32px" style="position: absolute; z-index: 100252300; user-select: none; transform-origin: left top; transform: scale(1); left: 64px; top: 304px; width: 256px; height: 32px; outline: none;" data-coin-trip="?" data-flow="11"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0);">see-through</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin47925" data-js-name="coin47925" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="320px" data-width="64px" data-height="64px" style="position: absolute; z-index: 100252400; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 320px; width: 64px; height: 64px; outline: none;" data-coin-trip="?" data-file-include="f_bottomLeft.html" data-flow="12"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; margin: 0px; padding: 0px; border: none;" onclick="
try {
window.opener.boxShadowTop  = '-';
window.opener.boxShadowLeft = ' ';
window.opener.styleKey = 'u';
window.opener.kC = 0;
window.opener.cC = 0;
window.opener.boxShadowTuner();
} catch {};
">1</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin46547" data-js-name="coin46547" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="320px" data-top="320px" data-width="64px" data-height="64px" style="position: absolute; z-index: 100252500; user-select: none; transform-origin: left top; transform: scale(1); left: 320px; top: 320px; width: 64px; height: 64px; outline: none;" data-coin-trip="?" data-file-include="g_bottomRight.html" data-flow="13"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; margin: 0px; padding: 0px; border: none;" onclick="
try {
window.opener.boxShadowTop  = ' ';
window.opener.boxShadowLeft = ' ';
window.opener.styleKey = 'u';
window.opener.kC = 0;
window.opener.cC = 0;
window.opener.boxShadowTuner();
} catch {};
">3</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin55858" data-js-name="coin55858" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="64px" data-top="336px" data-width="256px" data-height="48px" style="position: absolute; z-index: 100252600; user-select: none; transform-origin: left top; transform: scale(1); left: 64px; top: 336px; width: 256px; height: 48px; outline: none;" data-coin-trip="?" data-file-include="c_boxShadowAlpha.html" data-flow="14"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 16px; outline: grey solid 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><input type="range" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" min="0" max="1" step="0.01" oninput="
try {
window.opener.boxShadowAlpha = this.value;
window.opener.styleKey = 'u';
window.opener.kC = 0;
window.opener.cC = 0;
window.opener.boxShadowTuner();
} catch {};
">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>
`;
