z_wizardCode.r_wizard = {};
z_wizardCode.r_wizard.a_documentation = `
Save startup files and in-program tutorial files without using the BASH script. The BASH scripts are much easier and more convenient but, some users might not understand, so this is a quick solution that might help to open it up to all users.
`;
z_wizardCode.r_wizard.b_code = `
<div id="coin61019" data-js-name="coin61019" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="320px" data-width="384px" data-height="64px" style="position: absolute; z-index: 100250000; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 320px; width: 384px; height: 64px; outline: none;" data-coin-trip="?" data-file-include="a_simpleStartupSave.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; border-radius: 64px; outline: grey solid 4px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
this.parentNode.parentNode.parentNode.remove();
saveStartupTutorial(1,false);
hotDog = false;
spaceViewOff([e,32,32,es,ec,ea]);
restorePointerEventsNone(); 
helpMenuOverlay.style.display='none'; 
interfaceLayer.style.display='none';
">save startup/tutorial</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent; transform: rotate(180deg);"></div></div>

<div id="coin21728" data-js-name="coin21728" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="0px" data-width="384px" data-height="320px" style="position: absolute; z-index: 100250000; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 0px; width: 384px; height: 320px; outline: none;" data-coin-trip="?"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: auto; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: left; background-color: transparent; color: rgb(0, 0, 0); font-size: 32px; text-shadow: rgba(63, 0, 0, 0.5) 0.01em 0.01em 2.05px; text-indent: 0em; padding: 16px;">This one works directly from the page that is being saved. (Note: There is a BASH script that does this same thing, only better. run '. ./2_b_clips_update' from BASH. If you use this and then use the BASH scripts to apply the header/footer, then you will find that it becomes duplicated. That's not so good. If you use this button, you need to intercept the file.) The idea is that the file which is saved will be able to act as a 'startup file'. This only works if the file is inside of the same directory as the program file. This way you can easily make up your own startup files or tutorial files for whatever purpose. Again, the best use will be by 'unwrapping' this part using the 'u' key. Then the button can become part of your custom interface. After that, you can just copy it in when you like to use it. The button will remove itself before the file is saved. So, do not feel troubled when it disappears. This way the button does not end up showing in your final saved file.</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>


`;
