                                                                          shelfMenuHTML.tab1.folderSelectors.style = "\n" + `<style>
.button_folder11button           { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII="); position: absolute; border: none; margin: none; padding: none; left:      27px; top:     37px; width:     72px; height:     31px; }
.button_folder11button:focus     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII=");  }
.button_folder11button:hover     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAAAfCAMAAABzuHs6AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAOlJREFUSInNlUEOxCAIRduy5v7XHSsKoiBmdJJhYQrBV/0iXtcf2rNt2HCQbIdEXzcZbJB8EEa2CKox32AN9EBkq1s7ptFBkKXrBPQmVpCa2Mjd6GpxM8g8HXj6Y4OCMSWYgvo4MCavvCwuBuEQB9Redgk1AUk0FYwJqh/IYgOn3lxrKAFRS/KGPbvHj8pnz9UzBJVq2Ab1M2THMu6BUEYXlKvjAKhN4TXWe7EOKsKCisi9kB/mfuSDxk2oYK/lD0H9PHjrfeQsgKye0aLUVakJgk0g7lFWW/cDyqUVffu6tkZvdvgOxpYoH19sGQ2yDQexAAAAAElFTkSuQmCC");  }
.button_folder11button:active    { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAAAfCAMAAABzuHs6AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAAOtJREFUSInNlUEOxCAIRRs3hKT3P++0oiAKYkYnGRamEHzVL+J1/aGlbcOGg2Q7JPq6yWCD5IMwskVQjfkGa6AEka1u7ZhGB0GWrhPQm1hBamIjtwhicjPIPB1I/bFBwZgSTEF9HBiTV14WF4NwiANqL7uEmoAk+hSMCaofyGIDp95caygBUUvyhj27x4/KZ8/VMwSVatgG9TNkxzLugVBGF5Sr4wCoTeE11nuxDirCgorIvZAf5n7kg8ZNqGCv5Q9B/Tx4633kLICsntGi1FWpCYJ9QNyjrLbuB5RLK/r2dW2N3uzwHYztoXwAyc845XKB1AUAAAAASUVORK5CYII="); }

.button_folder12button           { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII="); position: absolute; border: none; margin: none; padding: none; left:    101px; top:     37px; width:     94px; height:     28px; }
.button_folder12button:focus     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAAKxJREFUSInd1ksOgCAMBUBWpivuf1yNEXz9KARaNXajUhhJFTSlwMg5Ut/8WP4fQe7B9MU9iPHe5XiJx8JhKUtF2SW2dc4ee0qjtIlUUnoff1qKx9QML89Lk5H6Pk8BPBS7pkVqlCc2X/3WevLGopjk94PN15THo7V53a3JH5NV49jil6u7jmnzuBHAXVTpS4rtELc8QVciPg4Auug3waMwyjvFs3zotzbsT2EFXokZL36TTgMAAAAASUVORK5CYII=");  }
.button_folder12button:hover     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAJlJREFUSIntllEOgCAMQ+n9L+3XoN0QDYzEEPcl63gulRFL+ePsQHoIfUPDJ+LZOLbSHJUl5152z5WeYTknlUh/hW+sgGdpBe+fLdWRvo/HBjyZXWUnzeIh/cZTm4nvDMUivukBX6WMT9vHx7JHPGpS98nw++l2oBGeLwJ6S7DeJLkhhnhQKaD7CICbugU8E2bxWXEOftufwgV6NQKKuOYHnwAAAABJRU5ErkJggg==");  }
.button_folder12button:active    { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAAAA/wAQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOADSnEQEAAAAEHRSTlMA////////////////////wFCLQwAAAJJJREFUSIntklEOgCAMQ+eX97+xMTrWbRAFpmJCP4y03ZMsEk1NDawlWB/h8YQ519QRvZu3d98CBnsmUjMVeGE5PEY9ePvOViYaH08P4GHZKTZRK15iOn7ITBSFp3B82oDHRyzHjWSiOvx5WTenmgYvM9d49jiSFevVc+Q5JTx6tgBNKvQ68FhtxQfpXfzvtO6PDWIxBD3jAhZ1AAAAAElFTkSuQmCC"); }
</style>
`;