const

template         = {}; 
template.default = {}; 

template.default.background             = ""; 
template.default.backgroundColor        = "transparent";
template.default.color                  = "black";
template.default.textShadow             = ""; 
template.default.textAlign              = "left";
template.default.textIndent             = ""; 
template.default.fontSize               = "16px";
template.default.fontStyle              = ""; 
template.default.fontWeight             = ""; 
template.default.fontVariant            = ""; 
template.default.fontFamily             = ""; 

template.default.lineHeight             = ""; 
template.default.wordSpacing            = ""; 
template.default.letterSpacing          = ""; 

template.default.textTransform          = ""; 
template.default.direction              = ""; 
template.default.opacity                = "1";
template.default.paddingLeft            = "0px";
template.default.paddingRight           = "0px";
template.default.paddingTop             = "0px";
template.default.paddingBottom          = "0px";
template.default.borderTopLeftRadius    = "0px";
template.default.borderTopRightRadius   = "0px";
template.default.borderBottomLeftRadius = "0px";
template.default.borderBottomRightRadius= "0px";
template.default.outlineStyle           = "solid";
template.default.outlineWidth           = "0px";
template.default.outlineColor           = "grey";
template.default.outlineOffset          = "0px";
template.default.boxShadow              = ""; 
template.default.overflow               = "hidden";
template.default.userSelect             = "none";
template.default.anchorPosition         = ""; 
template.default.contenteditable        = "false";
template.default.transform              = ""; 

template.defaultIMG = {};

template.defaultIMG.background             = ""; 
template.defaultIMG.backgroundColor        = "transparent";
template.defaultIMG.color                  = "black";
template.defaultIMG.textShadow             = ""; 
template.defaultIMG.textAlign              = "left";
template.defaultIMG.textIndent             = ""; 
template.defaultIMG.fontSize               = "16px";
template.defaultIMG.fontStyle              = ""; 
template.defaultIMG.fontWeight             = ""; 
template.defaultIMG.fontVariant            = ""; 
template.defaultIMG.fontFamily             = ""; 

template.defaultIMG.lineHeight             = ""; 
template.defaultIMG.wordSpacing            = ""; 
template.defaultIMG.letterSpacing          = ""; 

template.defaultIMG.textTransform          = ""; 
template.defaultIMG.direction              = ""; 
template.defaultIMG.opacity                = "1";
template.defaultIMG.paddingLeft            = "0px";
template.defaultIMG.paddingRight           = "0px";
template.defaultIMG.paddingTop             = "0px";
template.defaultIMG.paddingBottom          = "0px";
template.defaultIMG.borderTopLeftRadius    = "0px";
template.defaultIMG.borderTopRightRadius   = "0px";
template.defaultIMG.borderBottomLeftRadius = "0px";
template.defaultIMG.borderBottomRightRadius= "0px";
template.defaultIMG.outlineStyle           = "solid";
template.defaultIMG.outlineWidth           = "0px";
template.defaultIMG.outlineColor           = "grey";
template.defaultIMG.outlineOffset          = "0px";
template.defaultIMG.boxShadow              = ""; 
template.defaultIMG.overflow               = "hidden";
template.defaultIMG.userSelect             = "none";
template.defaultIMG.anchorPosition         = ""; 
template.defaultIMG.contenteditable        = "false";
template.defaultIMG.transform              = ""; 

if (localStorage.getItem("template.default.background")) { template.default.background = localStorage.getItem("template.default.background"); }
if (localStorage.getItem("template.default.backgroundColor")) { template.default.backgroundColor = localStorage.getItem("template.default.backgroundColor"); }
if (localStorage.getItem("template.default.color")) { template.default.color = localStorage.getItem("template.default.color"); }
if (localStorage.getItem("template.default.textShadow")) { template.default.textShadow = localStorage.getItem("template.default.textShadow"); }
if (localStorage.getItem("template.default.textAlign")) { template.default.textAlign = localStorage.getItem("template.default.textAlign"); }
if (localStorage.getItem("template.default.textIndent")) { template.default.textIndent = localStorage.getItem("template.default.textIndent"); }
if (localStorage.getItem("template.default.fontSize")) { template.default.fontSize = localStorage.getItem("template.default.fontSize"); }
if (localStorage.getItem("template.default.fontStyle")) { template.default.fontStyle = localStorage.getItem("template.default.fontStyle"); }
if (localStorage.getItem("template.default.fontWeight")) { template.default.fontWeight = localStorage.getItem("template.default.fontWeight"); }
if (localStorage.getItem("template.default.fontVariant")) { template.default.fontVariant = localStorage.getItem("template.default.fontVariant"); }
if (localStorage.getItem("template.default.fontFamily")) { template.default.fontFamily = localStorage.getItem("template.default.fontFamily"); }
if (localStorage.getItem("template.default.lineHeight")) { template.default.lineHeight = localStorage.getItem("template.default.lineHeight"); }
if (localStorage.getItem("template.default.wordSpacing")) { template.default.wordSpacing = localStorage.getItem("template.default.wordSpacing"); }
if (localStorage.getItem("template.default.letterSpacing")) { template.default.letterSpacing = localStorage.getItem("template.default.letterSpacing"); }
if (localStorage.getItem("template.default.textTransform")) { template.default.textTransform = localStorage.getItem("template.default.textTransform"); }
if (localStorage.getItem("template.default.direction")) { template.default.direction = localStorage.getItem("template.default.direction"); }
if (localStorage.getItem("template.default.opacity")) { template.default.opacity = localStorage.getItem("template.default.opacity"); }
if (localStorage.getItem("template.default.paddingLeft")) { template.default.paddingLeft = localStorage.getItem("template.default.paddingLeft"); }
if (localStorage.getItem("template.default.paddingRight")) { template.default.paddingRight = localStorage.getItem("template.default.paddingRight"); }
if (localStorage.getItem("template.default.paddingTop")) { template.default.paddingTop = localStorage.getItem("template.default.paddingTop"); }
if (localStorage.getItem("template.default.paddingBottom")) { template.default.paddingBottom = localStorage.getItem("template.default.paddingBottom"); }
if (localStorage.getItem("template.default.borderTopLeftRadius")) { template.default.borderTopLeftRadius = localStorage.getItem("template.default.borderTopLeftRadius"); }
if (localStorage.getItem("template.default.borderTopRightRadius")) { template.default.borderTopRightRadius = localStorage.getItem("template.default.borderTopRightRadius"); }
if (localStorage.getItem("template.default.borderBottomLeftRadius")) { template.default.borderBottomLeftRadius = localStorage.getItem("template.default.borderBottomLeftRadius"); }
if (localStorage.getItem("template.default.borderBottomRightRadius")) { template.default.borderBottomRightRadius = localStorage.getItem("template.default.borderBottomRightRadius"); }
if (localStorage.getItem("template.default.outlineStyle")) { template.default.outlineStyle = localStorage.getItem("template.default.outlineStyle"); }
if (localStorage.getItem("template.default.outlineWidth")) { template.default.outlineWidth = localStorage.getItem("template.default.outlineWidth"); }
if (localStorage.getItem("template.default.outlineColor")) { template.default.outlineColor = localStorage.getItem("template.default.outlineColor"); }
if (localStorage.getItem("template.default.outlineOffset")) { template.default.outlineOffset = localStorage.getItem("template.default.outlineOffset"); }
if (localStorage.getItem("template.default.boxShadow")) { template.default.boxShadow = localStorage.getItem("template.default.boxShadow"); }
if (localStorage.getItem("template.default.overflow")) { template.default.overflow = localStorage.getItem("template.default.overflow"); }
if (localStorage.getItem("template.default.userSelect")) { template.default.userSelect = localStorage.getItem("template.default.userSelect"); }
if (localStorage.getItem("template.default.anchorPosition")) { template.default.anchorPosition = localStorage.getItem("template.default.anchorPosition"); }
if (localStorage.getItem("template.default.contenteditable")) { template.default.contenteditable = localStorage.getItem("template.default.contenteditable"); }
if (localStorage.getItem("template.default.transform")) { template.default.transform = localStorage.getItem("template.default.transform"); }
if (localStorage.getItem("template.defaultIMG.background")) { template.defaultIMG.background = localStorage.getItem("template.defaultIMG.background"); }
if (localStorage.getItem("template.defaultIMG.backgroundColor")) { template.defaultIMG.backgroundColor = localStorage.getItem("template.defaultIMG.backgroundColor"); }
if (localStorage.getItem("template.defaultIMG.color")) { template.defaultIMG.color = localStorage.getItem("template.defaultIMG.color"); }
if (localStorage.getItem("template.defaultIMG.textShadow")) { template.defaultIMG.textShadow = localStorage.getItem("template.defaultIMG.textShadow"); }
if (localStorage.getItem("template.defaultIMG.textAlign")) { template.defaultIMG.textAlign = localStorage.getItem("template.defaultIMG.textAlign"); }
if (localStorage.getItem("template.defaultIMG.textIndent")) { template.defaultIMG.textIndent = localStorage.getItem("template.defaultIMG.textIndent"); }
if (localStorage.getItem("template.defaultIMG.fontSize")) { template.defaultIMG.fontSize = localStorage.getItem("template.defaultIMG.fontSize"); }
if (localStorage.getItem("template.defaultIMG.fontStyle")) { template.defaultIMG.fontStyle = localStorage.getItem("template.defaultIMG.fontStyle"); }
if (localStorage.getItem("template.defaultIMG.fontWeight")) { template.defaultIMG.fontWeight = localStorage.getItem("template.defaultIMG.fontWeight"); }
if (localStorage.getItem("template.defaultIMG.fontVariant")) { template.defaultIMG.fontVariant = localStorage.getItem("template.defaultIMG.fontVariant"); }
if (localStorage.getItem("template.defaultIMG.fontFamily")) { template.defaultIMG.fontFamily = localStorage.getItem("template.defaultIMG.fontFamily"); }
if (localStorage.getItem("template.defaultIMG.lineHeight")) { template.defaultIMG.lineHeight = localStorage.getItem("template.defaultIMG.lineHeight"); }
if (localStorage.getItem("template.defaultIMG.wordSpacing")) { template.defaultIMG.wordSpacing = localStorage.getItem("template.defaultIMG.wordSpacing"); }
if (localStorage.getItem("template.defaultIMG.letterSpacing")) { template.defaultIMG.letterSpacing = localStorage.getItem("template.defaultIMG.letterSpacing"); }
if (localStorage.getItem("template.defaultIMG.textTransform")) { template.defaultIMG.textTransform = localStorage.getItem("template.defaultIMG.textTransform"); }
if (localStorage.getItem("template.defaultIMG.direction")) { template.defaultIMG.direction = localStorage.getItem("template.defaultIMG.direction"); }
if (localStorage.getItem("template.defaultIMG.opacity")) { template.defaultIMG.opacity = localStorage.getItem("template.defaultIMG.opacity"); }
if (localStorage.getItem("template.defaultIMG.paddingLeft")) { template.defaultIMG.paddingLeft = localStorage.getItem("template.defaultIMG.paddingLeft"); }
if (localStorage.getItem("template.defaultIMG.paddingRight")) { template.defaultIMG.paddingRight = localStorage.getItem("template.defaultIMG.paddingRight"); }
if (localStorage.getItem("template.defaultIMG.paddingTop")) { template.defaultIMG.paddingTop = localStorage.getItem("template.defaultIMG.paddingTop"); }
if (localStorage.getItem("template.defaultIMG.paddingBottom")) { template.defaultIMG.paddingBottom = localStorage.getItem("template.defaultIMG.paddingBottom"); }
if (localStorage.getItem("template.defaultIMG.borderTopLeftRadius")) { template.defaultIMG.borderTopLeftRadius = localStorage.getItem("template.defaultIMG.borderTopLeftRadius"); }
if (localStorage.getItem("template.defaultIMG.borderTopRightRadius")) { template.defaultIMG.borderTopRightRadius = localStorage.getItem("template.defaultIMG.borderTopRightRadius"); }
if (localStorage.getItem("template.defaultIMG.borderBottomLeftRadius")) { template.defaultIMG.borderBottomLeftRadius = localStorage.getItem("template.defaultIMG.borderBottomLeftRadius"); }
if (localStorage.getItem("template.defaultIMG.borderBottomRightRadius")) { template.defaultIMG.borderBottomRightRadius = localStorage.getItem("template.defaultIMG.borderBottomRightRadius"); }
if (localStorage.getItem("template.defaultIMG.outlineStyle")) { template.defaultIMG.outlineStyle = localStorage.getItem("template.defaultIMG.outlineStyle"); }
if (localStorage.getItem("template.defaultIMG.outlineWidth")) { template.defaultIMG.outlineWidth = localStorage.getItem("template.defaultIMG.outlineWidth"); }
if (localStorage.getItem("template.defaultIMG.outlineColor")) { template.defaultIMG.outlineColor = localStorage.getItem("template.defaultIMG.outlineColor"); }
if (localStorage.getItem("template.defaultIMG.outlineOffset")) { template.defaultIMG.outlineOffset = localStorage.getItem("template.defaultIMG.outlineOffset"); }
if (localStorage.getItem("template.defaultIMG.boxShadow")) { template.defaultIMG.boxShadow = localStorage.getItem("template.defaultIMG.boxShadow"); }
if (localStorage.getItem("template.defaultIMG.overflow")) { template.defaultIMG.overflow = localStorage.getItem("template.defaultIMG.overflow"); }
if (localStorage.getItem("template.defaultIMG.userSelect")) { template.defaultIMG.userSelect = localStorage.getItem("template.defaultIMG.userSelect"); }
if (localStorage.getItem("template.defaultIMG.anchorPosition")) { template.defaultIMG.anchorPosition = localStorage.getItem("template.defaultIMG.anchorPosition"); }
if (localStorage.getItem("template.defaultIMG.contenteditable")) { template.defaultIMG.contenteditable = localStorage.getItem("template.defaultIMG.contenteditable"); }
if (localStorage.getItem("template.defaultIMG.transform")) { template.defaultIMG.transform = localStorage.getItem("template.defaultIMG.transform"); }
