                                                                          shelfMenuHTML.tab6.folderSelectors.style = "\n" + `<style>
.button_folder61button           { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII="); position: absolute; border: none; margin: none; padding: none; left:      5px; top:     37px; width:     94px; height:     28px; }
.button_folder61button:focus     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII=");  }
.button_folder61button:hover     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII=");  }
.button_folder61button:active    { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII="); }
.button_folder62button           { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII="); position: absolute; border: none; margin: none; padding: none; left:    101px; top:     37px; width:     94px; height:     28px; }
.button_folder62button:focus     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII=");  }
.button_folder62button:hover     { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII=");  }
.button_folder62button:active    { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF4AAAAcCAMAAADfnPg7AAAAMFBMVEUAAACLiYMQHFK0hc0Ydb3u6jGL1u5zeXOsumpaAACkqqT2/+7/AP8Aoe7FwsWLOACBHZNbAAAAEHRSTlMA////////////////////wFCLQwAAABlJREFUSIntwTEBAAAAwqD1T20JT6AAAOBrCmQAAVRhqcwAAAAASUVORK5CYII="); }
</style>
`;
