z_wizardCode.f_wizard = {};
z_wizardCode.f_wizard.a_documentation = `
This one gets some of the tripartite setting buttons and then some different colour setting buttons.
`;
z_wizardCode.f_wizard.b_code = `
<div id="coin99084" data-js-name="coin99084" data-parent="coin80750" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="orchid" data-file-include="b_setPink.html" data-width="192px" data-height="48px" data-scale="1" style="position: absolute; z-index: 100251400; user-select: none; left: 0px; top: 0px; width: 192px; height: 48px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="0px" data-coin-trip="?" data-flow="0"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: orchid dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: orchid; font-weight: bold;" onclick="
try { 
window.opener.coinFocus.dataset.coinTrip=Ts1;
window.opener.readCoins();
window.opener.recoverColouration();
} catch {};
">set PINK</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin38846" data-js-name="coin38846" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="208px" data-top="0px" data-width="176px" data-height="112px" style="position: absolute; z-index: 100251500; user-select: none; transform-origin: left top; transform: scale(1); left: 208px; top: 0px; width: 176px; height: 112px; outline: none;" data-coin-trip="?" data-flow="1"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: auto; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: left; background-color: transparent; color: rgb(0, 0, 0); padding: 8px; font-size: 16px; text-shadow: rgba(127, 127, 127, 0.75) 0.5px 0.5px 0.5px;"><u>Notes for this Wizard:</u><h2>Use 'u' to unwrap this part.</h2>The colours are for specific destinations on the target part. The transfer happens immediately but, the one that is the most useful it the one marked 'general colour'. That one can be used with the 'TAB' key to drag the colour onto another part by using 'ctrl' or 'alt' to put it to either the 'text colour' or 'outline colour'. If you also use the 'shift' key, then it goes to the whole group. To apply it to the background colour, do not hold down any modifier keys, and just drag onto the desired part. Of course, set the colour in the box first.</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin00821" data-js-name="coin00821" data-parent="coin88131" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="a_setGrey.html" data-width="192px" data-height="48px" data-scale="1" style="position: absolute; z-index: 100251600; user-select: none; left: 0px; top: 48px; width: 192px; height: 48px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="48px" data-coin-trip="?" data-flow="2"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: grey dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: grey; font-weight: bold;" onclick="
try { 
window.opener.coinFocus.dataset.coinTrip=Ts0;
window.opener.readCoins();
window.opener.recoverColouration();
} catch {};
">set GREY</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin02159" data-js-name="coin02159" data-parent="coin29760" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="royalblue" data-file-include="c_setBlue.html" data-width="192px" data-height="48px" data-scale="1" style="position: absolute; z-index: 100251700; user-select: none; left: 0px; top: 96px; width: 192px; height: 48px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="96px" data-coin-trip="?" data-flow="3"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: royalblue dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: blue; font-weight: bold;" onclick="
try { 
window.opener.coinFocus.dataset.coinTrip=Ts2;
window.opener.readCoins();
window.opener.recoverColouration();
} catch {};
">set BLUE</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin87463" data-js-name="coin87463" data-drag-pull="backgroundColor" data-parent="" data-children="coin96199" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="208px" data-top="128px" data-width="176px" data-height="32px" style="position: absolute; z-index: 100251800; user-select: none; transform-origin: left top; transform: scale(1); left: 208px; top: 128px; width: 176px; height: 32px; outline: none;" data-coin-trip="?" data-flow="4"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; border-radius: inherit; outline: grey dashed 3px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: white; color: rgb(0, 0, 0); font-size: 24px; text-shadow: rgba(127, 127, 127, 0.75) 0.75px 0.75px 0.75px;">general colour</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin88131" data-js-name="coin88131" data-drag-pull="backgroundColor" data-parent="" data-children="coin00821" data-scale="1" data-finished-outline="none" data-outline-colour="seagreen" data-left="0px" data-top="144px" data-width="192px" data-height="48px" style="position: absolute; z-index: 100251900; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 144px; width: 192px; height: 48px; outline: none;" data-coin-trip="?" data-file-include="e_cycleColours.html" data-flow="5"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: seagreen dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: green; font-weight: bold;" onclick="
try { 
window.opener.swapColours();
} catch {};
">cycle COLOURS</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin80750" data-js-name="coin80750" data-drag-pull="backgroundColor" data-parent="" data-children="coin99084" data-scale="1" data-finished-outline="none" data-outline-colour="navy" data-left="0px" data-top="192px" data-width="192px" data-height="48px" style="position: absolute; z-index: 100252100; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 192px; width: 192px; height: 48px; outline: none;" data-coin-trip="?" data-file-include="d_setAllColours.html" data-flow="7"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; border-radius: 64px; outline: navy dashed 3px;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="font-size: 18px; font-family: monospace; width: 100%; height: 100%; margin: 0px; padding: 0px; border: none; color: black; font-weight: bold;" onclick="
try { 
window.opener.assignAllColours();
} catch {};
">set all COLOURS</button></div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin13449" data-js-name="coin13449" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="0px" data-top="256px" data-width="128px" data-height="32px" style="position: absolute; z-index: 100252200; user-select: none; transform-origin: left top; transform: scale(1); left: 0px; top: 256px; width: 128px; height: 32px; outline: none;" data-coin-trip="?" data-flow="8"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; border-radius: inherit; outline: grey dashed 3px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: white; color: rgb(0, 0, 0); font-size: 24px; text-shadow: rgba(127, 127, 127, 0.75) 0.75px 0.75px 0.75px;">Text Colour</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin15419" data-js-name="coin15419" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="128px" data-top="256px" data-width="128px" data-height="32px" style="position: absolute; z-index: 100252300; user-select: none; transform-origin: left top; transform: scale(1); left: 128px; top: 256px; width: 128px; height: 32px; outline: none;" data-coin-trip="?" data-flow="9"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey dashed 3px; border-radius: inherit; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: white; color: rgb(0, 0, 0); font-size: 24px; text-shadow: rgba(127, 127, 127, 0.75) 0.75px 0.75px 0.75px;">BG Colour</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin17014" data-js-name="coin17014" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="256px" data-top="256px" data-width="128px" data-height="32px" style="position: absolute; z-index: 100252400; user-select: none; transform-origin: left top; transform: scale(1); left: 256px; top: 256px; width: 128px; height: 32px; outline: none;" data-coin-trip="?" data-flow="10"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; border-radius: inherit; outline: grey dashed 3px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: white; color: rgb(0, 0, 0); font-size: 24px; text-shadow: rgba(127, 127, 127, 0.75) 0.75px 0.75px 0.75px;">Outline Colour</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin40296" data-js-name="coin40296" data-parent="coin77969" data-children="" data-finished-outline="none" data-drag-pull="div.style.color" data-wrapper="undefined" data-outline-colour="grey" data-file-include="g_FGcolour.html" data-width="128px" data-height="96px" data-scale="1" style="position: absolute; z-index: 100252500; user-select: none; left: 0px; top: 288px; width: 128px; height: 96px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="288px" data-coin-trip="?" data-flow="11"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 255, 76);"><input type="color" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" oninput="
this.parentNode.parentNode.parentNode.dataset.dragPull='div.style.color';
this.parentNode.style.color=this.value;
try {
window.opener.coinFocus.div.style.color=this.value;
} catch {};
">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin42168" data-js-name="coin42168" data-parent="coin77969" data-children="" data-finished-outline="none" data-drag-pull="div.style.backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="f_BGcolour.html" data-width="128px" data-height="96px" data-scale="1" style="position: absolute; z-index: 100252600; user-select: none; left: 128px; top: 288px; width: 128px; height: 96px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="128px" data-top="288px" data-coin-trip="?" data-flow="12"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);"><input type="color" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" oninput="
this.parentNode.parentNode.parentNode.dataset.dragPull='div.style.backgroundColor';
this.parentNode.style.backgroundColor=this.value;
try {
window.opener.coinFocus.div.style.backgroundColor=this.value;
} catch {};
">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin77969" data-js-name="coin77969" data-drag-pull="main.style.outlineColor" data-parent="" data-children="coin40296,coin42168" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="256px" data-top="288px" data-width="128px" data-height="96px" style="position: absolute; z-index: 100252700; user-select: none; transform-origin: left top; transform: scale(1); left: 256px; top: 288px; width: 128px; height: 96px; outline: none;" data-coin-trip="?" data-flow="13" data-file-include="h_outlineColour.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block; outline-color: rgb(125, 125, 125);"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><input type="color" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" oninput="
this.parentNode.parentNode.parentNode.dataset.dragPull='main.style.outlineColor';
this.parentNode.parentNode.style.outlineColor=this.value;
try {
window.opener.coinFocus.main.style.outlineColor=this.value;
} catch {};
">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin96199" data-js-name="coin96199" data-parent="coin87463" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="I_input_color_general.html" data-width="176px" data-height="96px" data-scale="1" style="position: absolute; z-index: 100252800; user-select: none; left: 208px; top: 160px; width: 176px; height: 96px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="208px" data-top="160px" data-coin-trip="?" data-flow="6"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: rgb(0, 255, 0); color: rgb(0, 0, 0);"><input type="color" style="width: 100%; height: 100%; margin: 0; padding: 0; border: 0;" oninput="this.parentNode.style.backgroundColor = this.value;">
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>
`;
