z_wizardCode.k_wizard = {};
z_wizardCode.k_wizard.a_documentation = `
This is the same basic stuff, directly from what the numpad tuner would accomplish.
`;
z_wizardCode.k_wizard.b_code = `
<div id="coin15076" data-js-name="coin15076" data-parent="coin14220" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="c_numpad7.html" data-width="80px" data-height="80px" data-scale="1" style="position: absolute; z-index: 100251200; user-select: none; left: 0px; top: 0px; width: 80px; height: 80px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="0px" data-coin-trip="?" data-flow="0"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 103;
window.opener.cC = 55;
window.opener.edgeTuner();
} catch {};
">↖</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin34614" data-js-name="coin34614" data-parent="coin14220" data-children="coin48113" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="d_numpad8.html" data-width="160px" data-height="80px" data-scale="1" style="position: absolute; z-index: 100251300; user-select: none; left: 112px; top: 0px; width: 160px; height: 80px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="112px" data-top="0px" data-coin-trip="?" data-flow="1"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 104;
window.opener.cC = 56;
window.opener.edgeTuner();
} catch {};
">↑</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin20204" data-js-name="coin20204" data-parent="coin14220" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="e_numpad9.html" data-width="80px" data-height="80px" data-scale="1" style="position: absolute; z-index: 100251400; user-select: none; left: 304px; top: 0px; width: 80px; height: 80px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="304px" data-top="0px" data-coin-trip="?" data-flow="2"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 105;
window.opener.cC = 57;
window.opener.edgeTuner();
} catch {};
">↗</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin08115" data-js-name="coin08115" data-parent="coin94129" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="undefined" data-width="224px" data-height="32px" data-scale="1" style="position: absolute; z-index: 100251500; user-select: none; left: 80px; top: 80px; width: 224px; height: 32px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="80px" data-top="80px" data-coin-trip="?" data-flow="3"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0);">Rotations</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin43896" data-js-name="coin43896" data-parent="coin14220" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="f_numpad4.html" data-width="80px" data-height="160px" data-scale="1" style="position: absolute; z-index: 100251600; user-select: none; left: 0px; top: 112px; width: 80px; height: 160px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="112px" data-coin-trip="?" data-flow="4"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 100;
window.opener.cC = 52;
window.opener.edgeTuner();
} catch {};
">←</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin66140" data-js-name="coin66140" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="112px" data-top="112px" data-width="64px" data-height="64px" style="position: absolute; z-index: 100251700; user-select: none; transform-origin: left top; transform: scale(1); left: 112px; top: 112px; width: 64px; height: 64px; outline: none;" data-coin-trip="?" data-flow="5" data-file-include="a_numpadSlash.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 111;
window.opener.cC = 47;
window.opener.edgeTuner();
} catch {};
">z-</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin60929" data-js-name="coin60929" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="208px" data-top="112px" data-width="64px" data-height="64px" style="position: absolute; z-index: 100251800; user-select: none; transform-origin: left top; transform: scale(1); left: 208px; top: 112px; width: 64px; height: 64px; outline: none;" data-coin-trip="?" data-flow="6" data-file-include="b_numpadStar.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0deg" data-rotate-y="0deg" data-rotate-z="0deg" data-translate-z="0px" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block; transform: perspective(1536px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) translateZ(0px);"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 106;
window.opener.cC = 42;
window.opener.edgeTuner();
} catch {};
">z+</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin14220" data-js-name="coin14220" data-drag-pull="backgroundColor" data-parent="" data-children="coin15076,coin16683,coin18125,coin20204,coin23088,coin26191,coin34614,coin43896" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="304px" data-top="112px" data-width="80px" data-height="160px" style="position: absolute; z-index: 100251900; user-select: none; transform-origin: left top; transform: scale(1); left: 304px; top: 112px; width: 80px; height: 160px; outline: none;" data-coin-trip="?" data-flow="7" data-file-include="h_numpad6.html"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 102;
window.opener.cC = 54;
window.opener.edgeTuner();
} catch {};
">→</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin14459" data-js-name="coin14459" data-drag-pull="backgroundColor" data-parent="" data-children="" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="112px" data-top="208px" data-width="160px" data-height="64px" style="position: absolute; z-index: 100252000; user-select: none; transform-origin: left top; transform: scale(1); left: 112px; top: 208px; width: 160px; height: 64px; outline: none;" data-coin-trip="?" data-file-include="g_numpad5.html" data-flow="8"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; border-radius: 16px; outline: grey solid 3px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 101;
window.opener.cC = 53;
window.opener.edgeTuner();
} catch {};
">clear</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin94129" data-js-name="coin94129" data-drag-pull="backgroundColor" data-parent="" data-children="coin08115" data-scale="1" data-finished-outline="none" data-outline-colour="grey" data-left="80px" data-top="272px" data-width="224px" data-height="32px" style="position: absolute; z-index: 100252100; user-select: none; transform-origin: left top; transform: scale(1); left: 80px; top: 272px; width: 224px; height: 32px; outline: none;" data-coin-trip="?" data-flow="9"><a data-name="anchor" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: center; background-color: transparent; color: rgb(0, 0, 0);">Rotations</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin16683" data-js-name="coin16683" data-parent="coin14220" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="i_numpad1.html" data-width="80px" data-height="80px" data-scale="1" style="position: absolute; z-index: 100252200; user-select: none; left: 0px; top: 304px; width: 80px; height: 80px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="0px" data-top="304px" data-coin-trip="?" data-flow="10"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 97;
window.opener.cC = 49;
window.opener.edgeTuner();
} catch {};
">↙</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin48113" data-js-name="coin48113" data-parent="coin34614" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="j_numpad2.html" data-width="160px" data-height="80px" data-scale="1" style="position: absolute; z-index: 100252300; user-select: none; left: 112px; top: 304px; width: 160px; height: 80px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="112px" data-top="304px" data-coin-trip="?" data-flow="11"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 98;
window.opener.cC = 50;
window.opener.edgeTuner();
} catch {};
">↓</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>

<div id="coin18125" data-js-name="coin18125" data-parent="coin14220" data-children="" data-finished-outline="none" data-drag-pull="backgroundColor" data-wrapper="undefined" data-outline-colour="grey" data-file-include="k_numpad3.html" data-width="80px" data-height="80px" data-scale="1" style="position: absolute; z-index: 100252400; user-select: none; left: 304px; top: 304px; width: 80px; height: 80px; transform-origin: left top; transform: scale(1); outline: none;" data-angle="0" data-left="304px" data-top="304px" data-coin-trip="?" data-flow="12"><a data-name="anchor" style="position: absolute; z-index: 0; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px; margin: 0px; font-size: 32px; font-family: monospace; color: rgb(0, 0, 0); text-align: left; background-color: transparent; opacity: 1;"></a><div data-name="main" data-perspective="1536px" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-translate-z="0" style="position: absolute; z-index: 100; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 100%; border: none; transform-origin: center center; outline: grey solid 3px; border-radius: 16px; display: block;"><button data-name="button" style="position: absolute; z-index: 300; left: 0px; top: 0px; width: 100%; height: 100%; border: none; display: none; background-color: transparent; color: rgb(222, 255, 28); text-shadow: black 2px 2px 2px, black -2px 2px 2px, black 2px -2px 2px, black -2px -2px 2px; font-size: 24px; font-weight: bold;"></button><div data-name="div" style="position: absolute; z-index: 200; left: 0px; top: 0px; width: 100%; height: 100%; box-sizing: border-box; border: none; text-align: justify; background-color: transparent; color: rgb(0, 0, 0);"><button class="xqnBTN" style="width: 100%; height: 100%; font: inherit; margin: 0px; padding: 0px; border: none; color: inherit;" onclick="
try {
window.opener.kC = 99;
window.opener.cC = 51;
window.opener.edgeTuner();
} catch {};
">↘</button>
</div><img data-name="img" alt="" style="position: absolute; display: none; z-index: 100; left: 0px; top: 0px; width: 100%; height: 100%; border: none; background-color: transparent;"></div></div>
`;
